import React, { useEffect, useRef, useState } from "react";
import type { YujingSettings } from "../../shared/types";
import type { AtmosphereAudio } from "./audio";
type Props={cfg:YujingSettings;effectiveMood:Exclude<YujingSettings['mood'],'auto'>;update:(patch:Partial<YujingSettings>)=>void;close:()=>void;anchor:HTMLElement|null;game:()=>void;picker:()=>void;quotes:string[];manual:string;setManual:(v:string)=>void;updateQuotes:()=>void;temporary:number;pickQuote:()=>void;clearQuote:()=>void;selectedText:string;capture:()=>void;reading:boolean;chapter:boolean;sound:string;audio:React.MutableRefObject<AtmosphereAudio|undefined>;energyBar:React.RefObject<HTMLDivElement>;run:(p:Promise<unknown>)=>void;failed:boolean;message:string};
const scenes=[['wind','风中的句子'],['ocean','海的慢呼吸'],['island','书页留影'],['orbit','词语星轨']] as const;
export function AtmosphereSettings(p:Props){
 const {cfg,update}=p,[tab,setTab]=useState('picture'),[position,setPosition]=useState({left:16,top:72}),card=useRef<HTMLElement>(null),first=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const place=()=>{const r=p.anchor?.getBoundingClientRect(),width=Math.min(430,innerWidth-24),left=r?(r.right+width+16<innerWidth?r.right+12:Math.max(12,Math.min(r.left,innerWidth-width-12))):Math.max(12,(innerWidth-width)/2),top=innerWidth<760?12:r?Math.max(12,Math.min(r.top,innerHeight-620)):72;setPosition({left,top});};place();window.addEventListener('resize',place);first.current?.focus();return()=>{window.removeEventListener('resize',place);if(p.anchor?.isConnected)p.anchor.focus();};},[]);
 useEffect(()=>{if(tab==='text'&&cfg.scene!=='wind')setTab('picture');},[cfg.scene,tab]);
 const begin=(method:()=>Promise<unknown>)=>{update({enabled:true});p.run(method());};
 return <aside ref={card} className="yj-panel" role="dialog" aria-modal="false" aria-label="调节气候" style={{left:position.left,top:position.top,maxHeight:`calc(100dvh - ${position.top+12}px)`}}><div className="yj-panel-title"><div><small>跃境 · 自己的阅读风景</small><h2>调节气候</h2></div><button ref={first} aria-label="关闭气候设置" onClick={p.close}>×</button></div><label className="yj-check yj-main-switch"><input type="checkbox" checked={cfg.enabled} onChange={e=>update({enabled:e.target.checked})}/>开启跃境背景</label>
  <div className="yj-scene-picks">{scenes.map(([id,title])=><button key={id} aria-pressed={cfg.scene===id} onClick={()=>update({enabled:true,scene:id})}>{title}</button>)}</div>
  <nav className="yj-settings-tabs" role="tablist" aria-label="跃境设置分类">{[['picture','画面'],...(cfg.scene==='wind'?[['text','文字']]:[]),['sound','声音'],['performance','性能']].map(([id,name])=><button key={id} role="tab" tabIndex={tab===id?0:-1} id={'yj-tab-'+id} aria-controls={'yj-page-'+id} aria-selected={tab===id} onClick={()=>setTab(id)} onKeyDown={e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const tabs=Array.from(e.currentTarget.parentElement!.querySelectorAll<HTMLButtonElement>('button')),index=tabs.indexOf(e.currentTarget),next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(index+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length;tabs[next].click();tabs[next].focus();}}>{name}</button>)}</nav>
  <div className="yj-settings-page" role="tabpanel" id="yj-page-picture" aria-labelledby="yj-tab-picture" hidden={tab!=='picture'}>
   <label className="yj-check"><input type="checkbox" checked={cfg.matchTheme===true} onChange={e=>update({matchTheme:e.target.checked})}/>背景跟随应用主题</label><label>光的时刻<select value={cfg.mood} onChange={e=>update({mood:e.target.value as YujingSettings['mood']})}><option value="auto">跟随电脑时间</option><option value="day">晴海 · 剔透青蓝</option><option value="dawn">日出 · 桃金</option><option value="dusk">黄昏 · 暖霞</option><option value="night">夜航 · 深蓝</option></select></label>{cfg.mood==='auto'&&<p className="yj-help">本机时间 · 当前{{dawn:'日出',day:'晴海',dusk:'黄昏',night:'夜航'}[p.effectiveMood]}。05–08 日出，08–17 晴海，17–20 黄昏，其余夜航；可随时改为手动。</p>}
   {cfg.scene==='ocean'&&<><label>天空的表情<select aria-label="天空的表情" value={cfg.weather??'radiant'} onChange={e=>update({weather:e.target.value as YujingSettings['weather']})}><option value="radiant">辉光 · 云间的光</option><option value="clouds">流云 · 柔和天光</option><option value="clear">晴空 · 清澈远方</option></select></label><label className="yj-check"><input type="checkbox" checked={cfg.bottlesEnabled!==false} onChange={e=>update({bottlesEnabled:e.target.checked})}/>海面上的漂流瓶</label></>}
   {cfg.scene==='orbit'&&<><label>轨道词语数<input aria-label="轨道词语数" type="range" min="8" max="48" step="1" value={cfg.planetCount} onChange={e=>update({planetCount:Number(e.target.value)})}/></label><p className="yj-help">主页也可按住恒星左键，慢慢点亮后开始练习。</p></>}
   <button className="yj-primary" onClick={p.game}>进入词语星轨 · 快速刷词</button><button onClick={p.picker}>查看词库 · 自选本轮词语</button>
   <label>背景强度<input type="range" min=".1" max="1" step=".05" value={cfg.intensity} onChange={e=>update({intensity:Number(e.target.value)})}/></label><label>主页栏底色浓度 · {Math.round((cfg.chromeOpacity??.34)*100)}%<input aria-label="主页栏底色浓度" type="range" min="0" max="1" step=".05" value={cfg.chromeOpacity??.34} onChange={e=>update({chromeOpacity:Number(e.target.value)})}/></label><label>阅读底色不透明度 · {Math.round(cfg.readerOpacity*100)}%<input aria-label="阅读底色不透明度" type="range" min="0" max="1" step=".05" value={cfg.readerOpacity} onChange={e=>update({readerOpacity:Number(e.target.value)})}/></label><label>与原有图片背景<select value={cfg.blend} onChange={e=>update({blend:e.target.value as 'art'|'mix'})}><option value="art">跃境暂时替换图片</option><option value="mix">跃境与图片叠加</option></select></label>
  </div>
  {cfg.scene==='wind'&&<div className="yj-settings-page" role="tabpanel" id="yj-page-text" aria-labelledby="yj-tab-text" hidden={tab!=='text'}><label>吹来的文字<select value={cfg.source} onChange={e=>update({source:e.target.value as YujingSettings['source']})}><option value="highlights">我的划线</option><option value="chapter" disabled={!p.chapter}>当前阅读章节</option><option value="manual">手动摘录</option></select></label><p className="yj-help">{p.quotes.length} 条来源 · 完整成组，按长度停留 8–18 秒；长文原位续页。鼠标接触会轻轻拨动局部文字。</p>{cfg.source==='manual'&&<><textarea aria-label="手动摘录" rows={4} value={p.manual} onChange={e=>p.setManual(e.target.value)} maxLength={12000}/><p className="yj-help">一行一条，单条最多 2000 字；播放时自动分段。</p><button onClick={p.updateQuotes}>更新摘录</button></>}<button className="yj-primary" onClick={p.pickQuote}>临时选句</button>{p.temporary>0&&<button onClick={p.clearQuote}>取消临时选句 · 恢复文字来源</button>}{p.quotes[0]&&<blockquote className="yj-source-preview">{p.quotes[0]}</blockquote>}{p.reading&&<button className="yj-capture" disabled={!p.selectedText.trim()} onPointerDown={e=>e.preventDefault()} onClick={p.capture}>选句入风 · 保存划线</button>}</div>}
  <div className="yj-settings-page" role="tabpanel" id="yj-page-sound" aria-labelledby="yj-tab-sound" hidden={tab!=='sound'}><div className="yj-audio-status" role="status"><span className="yj-audio-state">{p.sound}</span><div className="yj-energy" aria-label="声音能量"><div ref={p.energyBar}/></div></div><p className="yj-help">低音推动波浪，音乐点亮星轨。先播放音乐，再连接声音。</p><button className="yj-primary" disabled={p.sound.startsWith('等待授权')} onClick={()=>begin(()=>p.audio.current!.share(true))}>连接电脑媒体声音</button><p className="yj-help">Windows Edge / Chrome：在弹出的授权窗口选「整个屏幕」，开启「共享系统音频」。无需展开播放器或保持它在前台。</p><div className="yj-two"><button disabled={p.sound.startsWith('等待授权')} onClick={()=>begin(()=>p.audio.current!.share(false))}>连接标签页音乐</button><button onClick={()=>p.run(p.audio.current!.stop())}>停止 / 断开</button></div><label className="yj-file">选择本地音乐 · 无需共享<input type="file" accept="audio/*" onChange={e=>{const file=e.target.files?.[0];if(file)begin(()=>p.audio.current!.file(file));e.target.value='';}}/></label><button onClick={()=>begin(()=>p.audio.current!.demo())}>试听律动</button><p className="yj-help">授权由浏览器管理。只分析声音，不读取、保存或传送画面；不使用麦克风。选屏幕声音时可能同时包含通知声。</p><label>试听 / 文件音量<input type="range" min="0" max=".5" step=".01" defaultValue=".12" onChange={e=>p.audio.current?.setVolume(Number(e.target.value))}/></label><label>律动幅度<input type="range" min=".5" max="3" step=".1" value={cfg.soundStrength} onChange={e=>update({soundStrength:Number(e.target.value)})}/></label></div>
  <div className="yj-settings-page" role="tabpanel" id="yj-page-performance" aria-labelledby="yj-tab-performance" hidden={tab!=='performance'}><label>画面品质<select aria-label="画面品质" value={cfg.quality??'auto'} onChange={e=>update({quality:e.target.value as YujingSettings['quality']})}><option value="auto">自动 · 根据设备调整</option><option value="battery">节能 · 更轻的画面</option><option value="high">精致 · 更多细节</option></select></label><p className="yj-help">海面与星轨实时绘制。自动模式会减小画面分辨率，阅读时降低帧率；切到其他标签页就停止绘制。节能模式还会减少海面网格与折射成本。</p><label>流动速度<input aria-label="流动速度" type="range" min="0" max="1.5" step=".1" value={cfg.speed} onChange={e=>update({speed:Number(e.target.value)})}/></label><button onClick={()=>update({paused:!cfg.paused})}>{cfg.paused?'继续流动':'暂停流动'}</button><p className="yj-help">暂停后只在设置变化时重绘。句子的可读停留时间不随流速缩短。</p></div>
  {p.failed&&<p role="alert">此浏览器未能启动 3D，可使用文字风景或关闭跃境。</p>}{p.message&&<p className="yj-message" role="status">{p.message}</p>}{cfg.enabled&&<button className="yj-off" onClick={()=>{update({enabled:false});p.close();}}>关闭跃境 · 恢复普通阅读</button>}
 </aside>;
}
