import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Yujing} from './Yujing';
import {DEFAULT_YUJING} from '../../shared/defaults';
import type {Book,ReaderNote,VocabItem,YujingSettings} from '../../shared/types';
import './lab.css';
const book:Book={id:'lab-book',title:'The Quiet Journey',filePath:'original-demo.md',fileType:'md',importedAt:'2026-10-04',updatedAt:'2026-10-04',missing:false};
const paragraphs=['The train moved slowly out of the city. Beyond the glass, buildings gave way to gardens, and then to fields that held the last gold of the afternoon. Mara opened her book, but for a moment she did not read.','A sentence can be a small window into another life. She had written those words in the margin yesterday. Now the actual window seemed to answer: the hills appeared, stayed for a breath, and quietly slipped away.','She let the page rest beneath her hand. There was no need to hurry. Somewhere between the words and the moving landscape, her attention found a softer pace.'];
const entries=[['serendipity','意外发现美好事物的幸运','A quiet detour became a moment of serendipity.'],['luminous','发光的；明亮的','The luminous water held the last light of evening.'],['meander','蜿蜒；漫步','We let the conversation meander like a river.'],['resonance','共鸣；回响','One sentence found a quiet resonance within her.'],['tranquil','安静的；平和的','The tranquil island seemed to float beyond the clouds.'],['ephemeral','短暂的','Each ephemeral reflection left a trace in memory.'],['wander','漫游','She let her thoughts wander along the open page.'],['ripple','涟漪','One small ripple crossed the morning sea.'],['solitude','独处','Solitude gave her attention room to breathe.'],['reverie','遐想','The book carried him into a quiet reverie.'],['aureole','光晕','An aureole of warm light surrounded the distant moon.'],['horizon','地平线','The horizon waited beyond the turning page.']];
const vocab:VocabItem[]=entries.map(([word,chineseDef,sourceSentence],i)=>({id:'demo-'+i,notebookId:'demo',bookId:book.id,word,chineseDef,sourceSentence,createdAt:'2026-10-04'}));
function Lab(){const[cfg,save]=useState<YujingSettings>({...DEFAULT_YUJING,enabled:true,scene:'wind',mood:'dusk',intensity:1}),[view,setView]=useState<'library'|'reader'>('library'),[selected,setSelected]=useState(''),[notes,setNotes]=useState<ReaderNote[]>(paragraphs.map((selectedText,i)=>({id:'quote-'+i,bookId:book.id,chapterId:'one',chapterTitle:'A window left open',selectedText,lineStyle:'solid',color:'#e8bd83',createdAt:'2026-10-04'})));
 const home=()=>{setView('library');save(v=>({...v,scene:'wind'}));};
 return <div className="yj-lab" style={{"--yj-paper":`${Math.round(cfg.readerOpacity*100)}%`} as React.CSSProperties}><Yujing settings={cfg} save={v=>save(v as typeof cfg)} view={view} book={book} chapterText={paragraphs.join('\n\n')} notes={notes} vocab={vocab} notebooks={[{id:'demo',name:'实验词语',createdAt:'2026-10-04'}]} selectedText={selected} capture={async()=>{setNotes(n=>[{id:crypto.randomUUID(),bookId:book.id,chapterId:'one',chapterTitle:'A window left open',selectedText:selected,lineStyle:'solid',color:'#e8bd83',createdAt:'2026-10-04'},...n]);}} home={home} pageKey={view} lab/>
 <header className="yj-lab-header"><span>SkipReader · 跃境实验室</span><a href="./index.html">打开完整 SkipReader ↗</a></header>
 <main>{view==='library'?<section className="yj-lab-home"><small>READING ATMOSPHERES / 02</small><h1>书页之外，<br/>风景继续。</h1><p>剔透的海，云上的书岛，<br/>还有你亲手点亮的词语星轨。</p><button onClick={()=>setView('reader')}>进入一段阅读 ↗</button></section>:<section className="yj-lab-reader"><div><button onClick={home}>← 回到主页</button>{cfg.scene==='wind'&&<button disabled={!selected} onPointerDown={e=>e.preventDefault()} onClick={()=>{setNotes(n=>[{id:crypto.randomUUID(),bookId:book.id,chapterId:'one',chapterTitle:'A window left open',selectedText:selected,lineStyle:'solid',color:'#e8bd83',createdAt:'2026-10-04'},...n]);}}>选句入风</button>}</div><article onMouseUp={()=>setSelected(getSelection()?.toString().trim()||'')}><small>ORIGINAL TEXT · THE QUIET JOURNEY</small><h2>A window left open</h2>{paragraphs.map(p=><p key={p}>{p}</p>)}</article></section>}
 <nav className="yj-lab-nav" aria-label="艺术场景">{(['wind','ocean','island','orbit'] as const).map((scene,i)=><button key={scene} data-scene={scene} aria-pressed={cfg.scene===scene} onClick={()=>save(v=>({...v,enabled:true,scene,mood:scene==='ocean'?'day':scene==='island'?'dusk':v.mood}))}>{['风中的句子','海的慢呼吸','云上书岛','词语星轨'][i]}</button>)}</nav></main><footer>独立实验 · 示例内容 · 关闭跃境可查看普通界面</footer></div>;
}
createRoot(document.getElementById('root')!).render(<Lab/>);
