import * as T from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import oceanURL from '../../../assets/yuejing/ocean.glb';
import islandURL from '../../../assets/yuejing/book-island.glb';
const palettes={day:{top:'#3888b9',horizon:'#d4e5e9',water:'#135f7e',sun:'#fff0c6'},dawn:{top:'#758caf',horizon:'#f2c5af',water:'#315d79',sun:'#ffddb0'},dusk:{top:'#4b6186',horizon:'#e6ac83',water:'#254e67',sun:'#f7cb98'},night:{top:'#071328',horizon:'#273b55',water:'#132e49',sun:'#b7cbe1'}};
const atmosphereGLSL=`vec3 atmosphere(vec3 d,vec3 top,vec3 horizon,vec3 glow,vec3 sun){float h=max(d.y,0.);vec3 c=mix(horizon,top,pow(h,.48));float s=max(dot(d,sun),0.);return c+glow*pow(s,6500.)*.95+glow*pow(s,22.)*.075;}`;
function disposeObject(root){const g=new Set(),m=new Set(),textures=new Set();root?.traverse(o=>{if(o.geometry)g.add(o.geometry);for(const a of o.material?Array.isArray(o.material)?o.material:[o.material]:[]){m.add(a);for(const v of Object.values(a))if(v?.isTexture)textures.add(v);}});textures.forEach(t=>t.dispose());g.forEach(v=>v.dispose());m.forEach(v=>v.dispose());}
export class SceneEngine {
 constructor(host,onPick,onFailure){
  this.host=host;this.onPick=onPick;this.onFailure=onFailure;this.quotes=[];this.words=[];this.energy={bass:0,mid:0,high:0,level:0};this.time=0;this.last=0;this.pulse=0;this.gustPower=0;this.pointer=new T.Vector2();this.settings={scene:'wind',mood:'dusk',speed:.7,intensity:.85,paused:false,soundStrength:1.8};this.reduced=matchMedia('(prefers-reduced-motion: reduce)');this.models={ocean:'idle',island:'idle'};this.disposed=false;
  this.canvas=document.createElement('canvas');this.canvas.setAttribute('aria-label','随风生成的书中摘录');host.append(this.canvas);this.ctx=this.canvas.getContext('2d');
  this.move=e=>{this.pointer.set(e.clientX/Math.max(1,this.width)*2-1,1-e.clientY/Math.max(1,this.height)*2);};
  this.pick=e=>{if(e.target.closest('button,input,select,textarea,a,[role=dialog],.reader-text,.yj-panel'))return;if(this.settings.game&&this.labels){const ray=new T.Raycaster();ray.setFromCamera(new T.Vector2(e.clientX/this.width*2-1,1-e.clientY/this.height*2),this.camera);const hit=ray.intersectObjects(this.labels)[0];if(hit)this.onPick?.(hit.object.userData.index);}else if(this.settings.scene==='wind')this.gust();else this.transition();};
  window.addEventListener('pointermove',this.move);window.addEventListener('pointerdown',this.pick);this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.resize();this.animate=this.animate.bind(this);this.frame=requestAnimationFrame(this.animate);
 }
 initialize3D(){if(this.renderer||this.renderError)return;try{
  this.renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.setClearColor(0,0);this.renderer.domElement.setAttribute('aria-label','Blender 海洋、云上书岛与词语星轨');this.host.append(this.renderer.domElement);this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(54,1,.1,800);this.scene.add(new T.HemisphereLight(0xc5e0e8,0x273f48,2));this.light=new T.DirectionalLight(0xffdfb3,2.6);this.light.position.set(-18,28,12);this.scene.add(this.light);
  this.sunDir=new T.Vector3(.29,.10,-1).normalize();this.sky=new T.Mesh(new T.SphereGeometry(700,32,16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{top:{value:new T.Color()},horizon:{value:new T.Color()},glow:{value:new T.Color()},sun:{value:this.sunDir}},vertexShader:'varying vec3 d;void main(){d=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec3 d;uniform vec3 top,horizon,glow,sun;${atmosphereGLSL}void main(){gl_FragColor=vec4(atmosphere(normalize(d),top,horizon,glow,sun),1.);\n#include <colorspace_fragment>\n}`}));this.scene.add(this.sky);
  this.oceanGroup=new T.Group();this.island=new T.Group();this.orbit=new T.Group();this.scene.add(this.oceanGroup,this.island,this.orbit);this.buildOcean();this.buildOrbit();this.buildClouds();this.resize();
 }catch(e){this.renderError=true;this.onFailure?.();}}
 buildOcean(){
  this.seaMaterial=new T.ShaderMaterial({uniforms:{time:{value:0},energy:{value:0},top:{value:new T.Color()},horizon:{value:new T.Color()},glow:{value:new T.Color()},sun:{value:this.sunDir},deep:{value:new T.Color()}},vertexShader:`
#include <common>
#include <morphtarget_pars_vertex>
varying vec3 wp;varying vec3 wn;uniform float time,energy;
void main(){
#include <beginnormal_vertex>
#include <morphnormal_vertex>
#include <begin_vertex>
#include <morphtarget_vertex>
transformed.y*=1.+energy*.55;objectNormal.xz*=1.+energy*.55;transformed.y+=sin(transformed.x*.62+transformed.z*.4+time*.7)*.008;
vec4 world=modelMatrix*vec4(transformed,1.);wp=world.xyz;wn=inverseTransformDirection(normalize(normalMatrix*objectNormal),viewMatrix);gl_Position=projectionMatrix*viewMatrix*world;}`,fragmentShader:`
 varying vec3 wp,wn;uniform float time,energy;uniform vec3 top,horizon,glow,sun,deep;${atmosphereGLSL}
 float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
 float noise(vec2 p){vec2 i=floor(p),f=fract(p),u=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),u.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1)),u.x),u.y);}
 float ripple(vec2 p){float detail=1./(1.+length(fwidth(wp.xz))*.8);vec2 drift=vec2(time*.11,time*-.08);return .11*noise(p*vec2(.7,1.4)+drift)+detail*(.035*noise(p*vec2(1.8,3.1)-drift*1.4)+.012*noise(p*4.5+drift*2.));}
 void main(){float a=ripple(wp.xz);vec3 n=normalize(wn+vec3((a-ripple(wp.xz+vec2(.025,0.)))/.025,0.,(a-ripple(wp.xz+vec2(0.,.025)))/.025));vec3 eye=normalize(cameraPosition-wp);float f=.02+.98*pow(1.-max(dot(n,eye),0.),5.);vec3 refl=atmosphere(reflect(-eye,n),top,horizon,glow,sun);float distance=length(wp-cameraPosition);float shore=exp(-distance*.045);vec3 water=mix(deep*.55,vec3(.018,.23,.26),shore*.62);vec3 color=mix(water,refl,f*.88);vec3 halfDir=normalize(sun+eye);float sparkle=pow(max(dot(n,halfDir),0.),650.);float scatter=pow(max(dot(n,halfDir),0.),90.)*.03;color+=glow*(sparkle*.9+scatter);color=mix(color,horizon,(1.-exp(-distance*.003))*.28);gl_FragColor=vec4(color,1.);
#include <colorspace_fragment>
}`});
  const fallback=new T.PlaneGeometry(480,480,90,90);fallback.rotateX(-Math.PI/2);this.water=new T.Mesh(fallback,this.seaMaterial);this.oceanGroup.add(this.water);
 }
 loadModel(name){if(this.models[name]!=='idle')return;this.models[name]='loading';new GLTFLoader().load(new URL(name==='ocean'?oceanURL:islandURL,import.meta.url).href,gltf=>{if(this.disposed){disposeObject(gltf.scene);return;}gltf.scene.updateMatrixWorld(true);
  if(name==='ocean'){let source;gltf.scene.traverse(o=>{if(o.isMesh&&!source)source=o;});if(!source){this.models.ocean='failed';return;}this.oceanGroup.remove(this.water);this.water.geometry.dispose();source.material.dispose();source.removeFromParent();this.water=source;this.water.material=this.seaMaterial;this.water.scale.set(4,1,4);this.oceanGroup.add(source);this.models.ocean='ready';}
  else{this.island.add(gltf.scene);this.pages=[];gltf.scene.traverse(o=>{if(o.name.startsWith('FloatingPage')){o.userData.baseY=o.position.y;this.pages.push(o);}});this.models.island='ready';}
 },undefined,()=>{if(!this.disposed){this.models[name]='failed';this.onFailure?.();}});}
 buildClouds(){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d'),gradient=ctx.createRadialGradient(64,64,0,64,64,64);gradient.addColorStop(0,'rgba(219,236,232,.8)');gradient.addColorStop(.45,'rgba(201,219,230,.32)');gradient.addColorStop(1,'rgba(201,219,230,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,128,128);const texture=new T.CanvasTexture(c);this.clouds=new T.Group();for(let i=0;i<18;i++){const s=new T.Sprite(new T.SpriteMaterial({map:texture,transparent:true,opacity:.26,depthWrite:false}));s.position.set(Math.sin(i*2.4)*23,-3+(i%4)*.7,-12-(i%5)*8);s.scale.set(13+(i%3)*4,4,1);this.clouds.add(s);}this.scene.add(this.clouds);}
 buildOrbit(){
  this.core=new T.Mesh(new T.IcosahedronGeometry(1.7,2),new T.MeshBasicMaterial({color:0xd7bd97,wireframe:true,transparent:true,opacity:.62}));this.orbit.add(this.core);
  for(let i=0;i<3;i++){const ring=new T.Mesh(new T.TorusGeometry(3.4+i*.65,.018,6,100),new T.MeshBasicMaterial({color:0xadc6cd,transparent:true,opacity:.38}));ring.rotation.set(.7+i*.8,.3+i*.6,i*.3);this.orbit.add(ring);}this.labels=[];this.planets=[];
  const points=[];let seed=1234;const rnd=()=>{seed=seed*16807%2147483647;return(seed-1)/2147483646;};for(let i=0;i<850;i++)points.push((rnd()-.5)*180,rnd()*85-30,-rnd()*140-20);const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(points,3));this.stars=new T.Points(geo,new T.PointsMaterial({color:0xeadcc1,size:.14,transparent:true,opacity:.7,depthWrite:false}));this.scene.add(this.stars);
  this.audioRing=new T.Group();for(let i=0;i<64;i++){const b=new T.Mesh(new T.BoxGeometry(.045,.1,.03),new T.MeshBasicMaterial({color:0xb7d4d5,transparent:true,opacity:.35}));const a=i/64*Math.PI*2;b.position.set(Math.cos(a)*3.2,Math.sin(a)*3.2,0);b.rotation.z=a-Math.PI/2;this.audioRing.add(b);}this.orbit.add(this.audioRing);
  this.sparks=new Float32Array(180*3);const sg=new T.BufferGeometry();sg.setAttribute('position',new T.BufferAttribute(this.sparks,3));this.sparkMesh=new T.Points(sg,new T.PointsMaterial({color:0xf6dab0,size:.075,transparent:true,opacity:0,depthTest:false}));this.scene.add(this.sparkMesh);
 }
 setWords(words,lit=new Set()){
  this.words=words.slice(0,48);this.lit=lit;if(!this.orbit)return;for(const o of [...this.labels,...this.planets]){this.orbit.remove(o);disposeObject(o);}this.labels=[];this.planets=[];
  this.words.forEach((word,i)=>{const c=document.createElement('canvas');c.width=512;c.height=110;const ctx=c.getContext('2d');ctx.font='38px Georgia';ctx.textAlign='center';ctx.fillStyle=lit.has(i)?'#f5d6a0':'#becdd4';ctx.fillText(word.slice(0,28),256,68);const l=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(c),transparent:true,depthTest:false}));l.scale.set(this.words.length>16?2.7:3.8,this.words.length>16?.58:.82,1);l.userData.index=i;this.orbit.add(l);this.labels.push(l);const planet=new T.Mesh(new T.SphereGeometry(.095+(i%3)*.025,10,8),new T.MeshBasicMaterial({color:lit.has(i)?0xe6c891:0x809caa,transparent:true,opacity:.75}));this.orbit.add(planet);this.planets.push(planet);});
 }
 configure(settings){const changed=this.settings.scene!==settings.scene;this.settings=settings;if(settings.scene!=='wind')this.initialize3D();this.canvas.hidden=settings.scene!=='wind';if(!this.renderer)return;this.renderer.domElement.hidden=settings.scene==='wind';this.oceanGroup.visible=settings.scene==='ocean';this.island.visible=settings.scene==='island';this.orbit.visible=settings.scene==='orbit';this.sky.visible=settings.scene!=='orbit';this.clouds.visible=settings.scene==='island';this.stars.visible=settings.scene==='orbit';this.scene.background=settings.scene==='orbit'?new T.Color('#102237'):null;this.audioRing.visible=false;this.sparkMesh.visible=settings.scene==='orbit';if(changed){this.pulse=0;this.burstTime=0;this.sparkMesh.material.opacity=0;this.renderer.clear();}
  const p=palettes[settings.mood]||palettes.day;for(const material of [this.sky.material,this.seaMaterial]){for(const k of ['top','horizon'])material.uniforms[k].value.set(p[k]);material.uniforms.glow.value.set(p.sun);}this.seaMaterial.uniforms.deep.value.set(p.water);if(settings.scene==='ocean'||settings.scene==='island')this.loadModel(settings.scene);if(this.labels.length!==this.words.length)this.setWords(this.words,this.lit);
 }
 resize(){const r=this.host.getBoundingClientRect();this.width=r.width||innerWidth;this.height=r.height||innerHeight;const d=Math.min(devicePixelRatio,1.5);this.canvas.width=this.width*d;this.canvas.height=this.height*d;this.ctx.setTransform(d,0,0,d,0,0);if(this.renderer){this.renderer.setSize(this.width,this.height);this.camera.aspect=this.width/this.height;this.camera.updateProjectionMatrix();}}
 gust(quote){if(quote){this.quotes=[quote,...this.quotes.filter(q=>q!==quote)].slice(0,24);this.time=7;}if(!this.settings.paused&&!this.reduced.matches)this.gustPower=1;this.wind();}
 transition(){if(!this.settings.paused&&!this.reduced.matches){this.pulse=.5;if(this.settings.scene==='wind')this.gustPower=.55;}}
 burst(index=0){if(this.settings.paused||this.reduced.matches)return;this.pulse=1;this.burstTime=1;this.sparkOrigin=this.planets?.[index]?.getWorldPosition(new T.Vector3())||new T.Vector3(5,4,0);this.sparkVel=Array.from({length:180},()=>new T.Vector3((Math.random()-.5)*7,(Math.random()-.5)*7,(Math.random()-.5)*5));}
 wind(){const c=this.ctx,w=this.width,h=this.height,t=this.time;const gradient=c.createLinearGradient(0,0,w,h);gradient.addColorStop(0,this.settings.mood==='night'?'#122536':'#263c46');gradient.addColorStop(1,this.settings.mood==='day'?'#4d737a':'#52615a');c.fillStyle=gradient;c.fillRect(0,0,w,h);const move=!this.settings.paused&&!this.reduced.matches,px=move?this.pointer.x:0,py=move?this.pointer.y:0;
  for(let i=0;i<55;i++){c.globalAlpha=.12;c.fillStyle='#e5d5b4';c.beginPath();c.arc(((i*.618%1)*w+t*(8+i%4*3)+px*12)%w,(i*.377%1)*h+Math.sin(t*.2+i)*15,.6+i%4*.45,0,Math.PI*2);c.fill();}
  if(!this.quotes.length){c.globalAlpha=.55;c.fillStyle='#d7e3dc';c.font='15px Microsoft YaHei';c.fillText('选一句书中文字，让风把它带来。',w*.48,h*.45);c.globalAlpha=1;return;}
  for(let row=0;row<7;row++){const cycle=t/17+row*.13,p=cycle%1,text=this.quotes[(Math.floor(cycle)+row)%this.quotes.length],words=text.match(/[\p{Script=Han}]|[^\s\p{Script=Han}]+|\s+/gu)||[text];c.font=`${w<650?17:23+row%3*5}px Georgia,Microsoft YaHei`;let x=w*.43+Math.sin(row*3.1)*w*.14-(p-.45)*w*.7+px*24+this.gustPower*px*55;const y=h*(.17+row*.095);for(let j=0;j<words.length;j++){const phase=p-j/words.length*.18;c.globalAlpha=Math.max(0,Math.min(phase*8,(1-phase)*5,1))*(row%2?.27:.43);c.fillStyle=row%3===0?'#f0cda0':'#e3ece7';c.fillText(words[j],x,y+Math.sin(t*.3+j*.5+row)*10+Math.pow(Math.max(0,p-.65),2)*160*Math.sin(j*.7)+py*22+this.gustPower*Math.sin(j*.5+row)*35);x+=c.measureText(words[j]).width;}}c.globalAlpha=1;
 }
 animate(ms){this.frame=requestAnimationFrame(this.animate);if(ms-this.last<1000/30)return;const dt=Math.min((ms-this.last)/1000||.03,.08);this.last=ms;if(this.disposed||document.hidden)return;const cfg=this.settings,moving=!cfg.paused&&!this.reduced.matches;if(moving)this.time+=dt*cfg.speed;const e=moving?this.energy.level:0,t=this.time;if(moving){this.pulse=Math.max(0,this.pulse-dt*.8);this.gustPower=Math.max(0,this.gustPower-dt*.32);}if(cfg.scene==='wind'){this.wind();return;}if(!this.renderer||this.renderError)return;
  const px=moving?this.pointer.x:0,py=moving?this.pointer.y:0;
  if(cfg.scene==='ocean'){this.camera.position.set(px*.5,3.0+py*.16,13);this.camera.lookAt(0,1.1,-100);this.seaMaterial.uniforms.time.value=t;this.seaMaterial.uniforms.energy.value=moving?this.energy.bass*cfg.soundStrength*.65:0;const weights=this.water.morphTargetInfluences;if(weights){weights.fill(0);const phase=t*.13,a=Math.floor(phase)%4,b=(a+1)%4,f=phase%1;if(a>0)weights[a-1]=1-f;if(b>0)weights[b-1]=f;}}
  if(cfg.scene==='island'){this.camera.position.set(px*.5,4.4+py*.25,18);this.camera.lookAt(1.4,.3,0);this.island.position.set(this.width<700?1:4.6,Math.sin(t*.25)*.13,0);this.island.rotation.y=Math.sin(t*.09)*.1+px*.04;this.island.scale.setScalar(this.width<700?.72:1);this.pages?.forEach((p,i)=>{p.position.y=p.userData.baseY+Math.sin(t*.35+i)*.17;});this.clouds.position.x=Math.sin(t*.03)*4;}
  if(cfg.scene==='orbit'){this.camera.position.set(0,5,20);this.camera.lookAt(0,5,0);this.orbit.position.set(this.width<700?1.3:7.3,this.width<700?6:5,0);this.orbit.scale.setScalar(this.width<700?.49:1);this.core.rotation.set(t*.07,t*.15,t*.04);this.core.scale.setScalar(1+e*.14+this.pulse*.06);this.labels.forEach((l,i)=>{const ring=Math.floor(i/10),a=t*(.085+ring*.01)+i*Math.PI*2/Math.min(10,this.words.length),r=this.lit.has(i)?2.6+ring*.45:4.2+ring*.5;l.position.set(Math.cos(a)*r,Math.sin(a*.7+i+ring)*2.6+ring*.3,Math.sin(a)*r*.45);this.planets[i].position.copy(l.position).add(new T.Vector3(0,-.24,0));});this.audioRing.visible=e>.002;this.audioRing.children.forEach((b,i)=>{const band=i%3===0?this.energy.bass:i%3===1?this.energy.mid:this.energy.high;b.scale.y=.3+band*cfg.soundStrength*8;});}
  if(this.burstTime>0&&moving){this.burstTime=Math.max(0,this.burstTime-dt);const age=1-this.burstTime;for(let i=0;i<180;i++){const p=this.sparkOrigin.clone().addScaledVector(this.sparkVel[i],age);this.sparks.set([p.x,p.y,p.z],i*3);}this.sparkMesh.geometry.attributes.position.needsUpdate=true;this.sparkMesh.material.opacity=this.burstTime;}
  this.renderer.render(this.scene,this.camera);
 }
 snapshot(){return{triangles:this.renderer?.info.render.triangles||0,time:this.time,energy:this.energy.level,activeScene:this.settings.scene,visibleLayers:[this.canvas.hidden?null:'wind',this.oceanGroup?.visible?'ocean':null,this.island?.visible?'island':null,this.orbit?.visible?'orbit':null].filter(Boolean),models:{...this.models},stars:this.stars?.geometry.attributes.position.count||0,planetCount:this.words.length,gust:this.gustPower,pointer:[this.pointer.x,this.pointer.y],geometries:this.renderer?.info.memory.geometries||0,targets:(this.labels||[]).map(l=>{const p=l.getWorldPosition(new T.Vector3()).project(this.camera);return{index:l.userData.index,x:(p.x+1)*this.width/2,y:(1-p.y)*this.height/2};})};}
 dispose(){this.disposed=true;cancelAnimationFrame(this.frame);window.removeEventListener('pointermove',this.move);window.removeEventListener('pointerdown',this.pick);this.resizeObserver.disconnect();disposeObject(this.scene);this.renderer?.dispose();this.renderer?.forceContextLoss();this.host.replaceChildren();}
}
