import * as T from 'three';
const skyGLSL=`vec3 atmosphere(vec3 d,vec3 top,vec3 horizon,vec3 sunColor,vec3 sunDir){float h=max(d.y,0.);vec3 c=mix(horizon,top,pow(h,.42));float s=max(dot(d,sunDir),0.);c+=sunColor*pow(s,7200.)*1.1+sunColor*pow(s,18.)*.09;return c;}`;
const palette={day:{top:'#398ab6',horizon:'#d3e6df',water:'#109eaa',sun:'#fff6d5',fog:'#aec9c0'},dawn:{top:'#709bb4',horizon:'#f7d6b6',water:'#30a4b0',sun:'#ffe1b0',fog:'#c4c4b4'},dusk:{top:'#4c6486',horizon:'#f7b27b',water:'#287d8d',sun:'#ffd293',fog:'#b6a899'},night:{top:'#07132f',horizon:'#293b59',water:'#174361',sun:'#a3c7e9',fog:'#26384f'}};
export class SceneEngine{
 constructor(host,onPick,onFailure){
  this.host=host;this.onPick=onPick;this.quotes=[];this.words=[];this.energy={bass:0,mid:0,high:0,level:0};this.time=0;this.last=0;this.pulse=0;this.pointer=new T.Vector2();this.settings={scene:'ocean',mood:'day',speed:.7,intensity:.65,paused:false};this.reduced=matchMedia('(prefers-reduced-motion: reduce)');this.resources=[];this.renderError=false;
  this.canvas=document.createElement('canvas');this.canvas.className='yj-wind';this.canvas.setAttribute('aria-label','随风生成的书中摘录');host.append(this.canvas);this.ctx=this.canvas.getContext('2d');
  try{this.renderer=new T.WebGLRenderer({alpha:true,antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;host.append(this.renderer.domElement);this.renderer.domElement.setAttribute('aria-label','三维海洋、车窗与词语星轨');this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(54,1,.1,500);this.build();}catch{this.renderError=true;onFailure?.();}
  this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.resize();
  this.move=e=>{this.pointer.set(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2);};
  this.pick=e=>{if(e.target.closest('button,input,select,textarea,a,[role=dialog],.reader-text,.yj-panel'))return;if(this.settings.game&&this.labels){const ray=new T.Raycaster();ray.setFromCamera(new T.Vector2(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2),this.camera);const hit=ray.intersectObjects(this.labels)[0];if(hit)this.onPick?.(hit.object.userData.index);}else if(this.settings.enabled&&!this.settings.paused)this.pulse=1;};
  window.addEventListener('pointermove',this.move);window.addEventListener('pointerdown',this.pick);this.animate=this.animate.bind(this);this.frame=requestAnimationFrame(this.animate);
 }
 build(){
  const s=this.scene;s.add(new T.HemisphereLight(0xe6edf3,0x405948,2.4));const light=new T.DirectionalLight(0xffe2b6,2.5);light.position.set(-40,60,-20);s.add(light);
  this.sunDir=new T.Vector3(.24,.12,-1).normalize();
  this.sky=new T.Mesh(new T.SphereGeometry(300,32,16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{top:{value:new T.Color()},horizon:{value:new T.Color()},sunColor:{value:new T.Color()},sunDir:{value:this.sunDir}},vertexShader:'varying vec3 d;void main(){d=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec3 d;uniform vec3 top,horizon,sunColor,sunDir;${skyGLSL}void main(){gl_FragColor=vec4(atmosphere(normalize(d),top,horizon,sunColor,sunDir),1.);
#include <colorspace_fragment>
}`}));s.add(this.sky);
  this.water=new T.Mesh(new T.PlaneGeometry(600,600,180,180),new T.ShaderMaterial({uniforms:{time:{value:0},energy:{value:0},top:{value:new T.Color()},horizon:{value:new T.Color()},sunColor:{value:new T.Color()},waterColor:{value:new T.Color()},sunDir:{value:this.sunDir}},vertexShader:`uniform float time,energy;varying vec3 wp;float wave(vec2 p){return sin(p.x*.17+p.y*.12+time*.8)*.34+sin(p.x*.35-p.y*.19-time*.65)*.16+sin(p.y*.7+p.x*.4+time*1.1)*.06;}void main(){vec3 p=position;vec4 worldBase=modelMatrix*vec4(p,1.);p.z=wave(worldBase.xz)*(1.+energy*.65);vec4 world=modelMatrix*vec4(p,1.);wp=world.xyz;gl_Position=projectionMatrix*viewMatrix*world;}`,fragmentShader:`uniform float time,energy;uniform vec3 top,horizon,sunColor,waterColor,sunDir;varying vec3 wp;${skyGLSL}
  float waves(vec2 p){float t=time;return sin(p.x*.17+p.y*.12+t*.8)*.34+sin(p.x*.35-p.y*.19-t*.65)*.16+sin(p.y*.7+p.x*.4+t*1.1)*.06+sin(p.x*1.4+p.y*.8+t*1.7)*.018;}
  void main(){vec2 p=wp.xz;float v=waves(p);vec3 n=normalize(vec3((v-waves(p+vec2(.08,0.)))/.08,1.,(v-waves(p+vec2(0.,.08)))/.08));vec3 eye=normalize(cameraPosition-wp);float fresnel=.025+.975*pow(1.-max(dot(n,eye),0.),4.);vec3 reflection=atmosphere(reflect(-eye,n),top,horizon,sunColor,sunDir);float distance=length(wp-cameraPosition);float depth=.8+distance*.075;vec2 bottom=p+n.xz*depth;float sand=sin(bottom.x*.6+sin(bottom.y*.3))*sin(bottom.y*.55)*.07;float caustic=pow(max(0.,sin(bottom.x*1.7+sin(bottom.y*1.3+time*.7))*sin(bottom.y*1.9+sin(bottom.x*.9-time*.5))),8.);vec3 bed=vec3(.72,.72,.5)+sand+caustic*.2;vec3 transmitted=mix(waterColor*.68,bed*vec3(.34,.90,1.),exp(-depth*.30));vec3 color=mix(transmitted,reflection,fresnel);vec3 halfDir=normalize(sunDir+eye);float spec=pow(max(dot(n,halfDir),0.),120.)*2.;color+=sunColor*spec;float foam=smoothstep(.49,.61,v)*.09;color+=vec3(foam);float haze=1.-exp(-distance*.003);color=mix(color,horizon,haze*.35);gl_FragColor=vec4(color,1.);
#include <colorspace_fragment>
}`}));this.water.rotation.x=-Math.PI/2;this.water.position.z=-135;s.add(this.water);
  this.land=new T.Group();s.add(this.land);this.buildTrain();this.orbit=new T.Group();s.add(this.orbit);this.buildOrbit();
  this.audioRing=new T.Group();s.add(this.audioRing);for(let i=0;i<64;i++){const bar=new T.Mesh(new T.BoxGeometry(.06,.1,.05),new T.MeshBasicMaterial({color:0xaddce4,transparent:true,opacity:.65}));const a=i/64*Math.PI*2;bar.position.set(Math.cos(a)*2.3,Math.sin(a)*2.3,0);bar.rotation.z=a-Math.PI/2;this.audioRing.add(bar);}this.audioRing.position.set(7,4,-4);
  const geometry=new T.BufferGeometry();this.sparks=new Float32Array(180*3);geometry.setAttribute('position',new T.BufferAttribute(this.sparks,3));this.sparkMesh=new T.Points(geometry,new T.PointsMaterial({color:0xffdfa3,size:.09,transparent:true,opacity:0,depthTest:false}));s.add(this.sparkMesh);
 }
 buildTrain(){
  const base=new T.Mesh(new T.PlaneGeometry(650,450),new T.MeshLambertMaterial({color:0x708063}));base.rotation.x=-Math.PI/2;base.position.set(0,-1.1,-130);this.land.add(base);
  for(let layer=0;layer<4;layer++){const group=new T.Group();group.userData.speed=.8+(3-layer)*.8;const geo=new T.PlaneGeometry(240,45,90,16);geo.rotateX(-Math.PI/2);const p=geo.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i);p.setY(i,(Math.sin(x*.024+layer*2.6)+Math.sin(x*.062+layer)*.4+1.4)*(2+layer*2.3)*Math.pow(Math.max(0,1-Math.abs(z)/22.5),.7));}geo.computeVertexNormals();const mat=new T.MeshLambertMaterial({color:[0x4f6d57,0x658275,0x80948c,0xa4afaa][layer]});for(let j=0;j<3;j++){const m=new T.Mesh(geo,mat);m.position.set((j-1)*240,0,-43-layer*42);group.add(m);}this.land.add(group);}
  this.scenery=new T.Group();this.scenery.userData.speed=10;this.land.add(this.scenery);const green=new T.MeshLambertMaterial({color:0x335341}),bark=new T.MeshLambertMaterial({color:0x675449}),poleMat=new T.MeshLambertMaterial({color:0x594b3c});
  const leafGeo=new T.SphereGeometry(1,12,9),leafMats=[0x4a6845,0x798344,0x9a7843,0xb39555].map(color=>new T.MeshLambertMaterial({color}));
  for(let i=0;i<46;i++){const tree=new T.Group();const h=3+(i*1.73%3);const trunk=new T.Mesh(new T.CylinderGeometry(.11,.17,h,7),bark);trunk.position.y=h/2;tree.add(trunk);if(i%4===0){for(let j=0;j<3;j++){const crown=new T.Mesh(new T.ConeGeometry(1.1-j*.23,2.6,10),green);crown.position.y=h*.58+j*.65;tree.add(crown);}}else{for(let j=0;j<5;j++){const crown=new T.Mesh(leafGeo,leafMats[(i+j)%4]);crown.position.set(Math.sin(j*2.4)*.6,h*.76+(j%2)*.8,Math.cos(j*2.4)*.55);crown.scale.set(1.1+(i%3)*.13,1.3+(j%2)*.2,1.1);tree.add(crown);}for(let j=0;j<2;j++){const branch=new T.Mesh(new T.CylinderGeometry(.04,.09,1.7,5),bark);branch.position.set(j?.3:-.3,h*.55,0);branch.rotation.z=j?-.5:.5;tree.add(branch);}}tree.position.set(i*11-250,-.7,-13-(i%5)*3.4);tree.userData.baseX=tree.position.x;this.scenery.add(tree);}
  this.village=new T.Group();this.village.userData.speed=3.8;this.land.add(this.village);for(let i=0;i<24;i++){const house=new T.Group(),facade=new T.MeshLambertMaterial({color:i%3?0xc5bc9e:0xd5c6b0});const body=new T.Mesh(new T.BoxGeometry(2.8,2.2,2.7),facade);body.position.y=1.1;house.add(body);const roof=new T.Mesh(new T.ConeGeometry(2.4,1.5,4),new T.MeshLambertMaterial({color:0x7e6454}));roof.rotation.y=Math.PI/4;roof.scale.z=.9;roof.position.y=2.9;house.add(roof);for(const x of [-.7,.7]){const win=new T.Mesh(new T.PlaneGeometry(.45,.6),new T.MeshBasicMaterial({color:0xf3d18b}));win.position.set(x,1.25,1.36);house.add(win);}house.position.set(i*18-220,-.65,-25-(i%3)*4);house.userData.baseX=house.position.x;this.village.add(house);}
  this.fences=new T.Group();this.fences.userData.speed=17;this.land.add(this.fences);for(let i=0;i<40;i++){const fence=new T.Group();const post=new T.Mesh(new T.BoxGeometry(.1,1.6,.12),poleMat);post.position.y=.8;fence.add(post);for(const y of [.5,1.1]){const beam=new T.Mesh(new T.BoxGeometry(7,.065,.08),poleMat);beam.position.set(3.5,y,0);fence.add(beam);}fence.position.set(i*7-140,-1,-5);fence.userData.baseX=fence.position.x;this.fences.add(fence);}
  // Terraced fields lie flat and pass beneath the village.
  const riverPoints=[];for(let i=0;i<=120;i++){const x=-300+i*5,z=-17+Math.sin(x*.022)*4;riverPoints.push(new T.Vector3(x,-.84,z-2.6),new T.Vector3(x,-.84,z+2.6));}const riverGeo=new T.BufferGeometry(),riverVertices=[],riverIndices=[];riverPoints.forEach(p=>riverVertices.push(p.x,p.y,p.z));for(let i=0;i<120;i++){const a=i*2;riverIndices.push(a,a+2,a+1,a+1,a+2,a+3);}riverGeo.setAttribute('position',new T.Float32BufferAttribute(riverVertices,3));riverGeo.setIndex(riverIndices);riverGeo.computeVertexNormals();this.land.add(new T.Mesh(riverGeo,new T.MeshPhongMaterial({color:0x7bb1bd,shininess:90,specular:0xe8c99b,side:T.DoubleSide})));
  for(let i=0;i<12;i++){const field=new T.Mesh(new T.PlaneGeometry(600,4),new T.MeshLambertMaterial({color:[0x81965d,0xa1a16b,0x667f5c,0xb2a879][i%4]}));field.rotation.x=-Math.PI/2;field.position.set(0,-1.02,-7-i*4);this.land.add(field);}
 }
 buildOrbit(){
  this.core=new T.Mesh(new T.IcosahedronGeometry(1.25,3),new T.MeshPhysicalMaterial({color:0x4a899f,metalness:.45,roughness:.22,transparent:true,opacity:.85}));this.orbit.add(this.core);const cage=new T.Mesh(new T.IcosahedronGeometry(1.4,1),new T.MeshBasicMaterial({color:0xa6e4eb,wireframe:true,transparent:true,opacity:.32}));this.orbit.add(cage);
  for(let i=0;i<3;i++){const ring=new T.Mesh(new T.TorusGeometry(2.5+i*.42,.016,7,100),new T.MeshBasicMaterial({color:0x9ed7e0,transparent:true,opacity:.45}));ring.rotation.set(.6+i*.7,.3+i*.5,i*.3);this.orbit.add(ring);}
  this.labels=[];this.planets=[];
 }
 setWords(words,lit=new Set()){
  if(!this.orbit)return;for(const o of [...this.labels,...this.planets]){this.orbit.remove(o);o.material.map?.dispose();o.material.dispose();o.geometry?.dispose();}this.labels=[];this.planets=[];this.words=words.slice(0,12);this.lit=lit;
  this.words.forEach((word,i)=>{const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d');ctx.font='34px Georgia';ctx.textAlign='center';ctx.fillStyle=lit.has(i)?'#ffe3a4':'#d8f4f3';ctx.fillText(word.slice(0,28),256,60);const sprite=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(c),transparent:true,depthTest:false}));sprite.scale.set(3.5,.656,1);sprite.userData.index=i;this.orbit.add(sprite);this.labels.push(sprite);const planet=new T.Mesh(new T.IcosahedronGeometry(.16,1),new T.MeshBasicMaterial({color:lit.has(i)?0xffd698:0x8ac5cc}));this.orbit.add(planet);this.planets.push(planet);});
 }
 configure(settings){this.settings=settings;if(!this.renderer)return;const p=palette[settings.mood]||palette.day;this.sky.material.uniforms.top.value.set(p.top);this.sky.material.uniforms.horizon.value.set(p.horizon);this.sky.material.uniforms.sunColor.value.set(p.sun);for(const k of ['top','horizon','sunColor'])this.water.material.uniforms[k].value.copy(this.sky.material.uniforms[k].value);this.water.material.uniforms.waterColor.value.set(p.water);this.scene.fog=settings.scene==='train'?new T.FogExp2(p.fog,.004):null;this.water.visible=settings.scene==='ocean';this.land.visible=settings.scene==='train';this.orbit.visible=settings.scene==='orbit';this.sky.visible=settings.scene!=='orbit';this.canvas.hidden=settings.scene!=='wind';this.renderer.domElement.hidden=settings.scene==='wind';}
 resize(){const r=this.host.getBoundingClientRect();this.width=r.width||innerWidth;this.height=r.height||innerHeight;const d=Math.min(devicePixelRatio,1.5);this.canvas.width=this.width*d;this.canvas.height=this.height*d;this.ctx.setTransform(d,0,0,d,0,0);if(this.renderer){this.renderer.setSize(this.width,this.height);this.camera.aspect=this.width/this.height;this.camera.updateProjectionMatrix();}}
 burst(index=0){if(this.settings.paused||this.reduced.matches)return;this.pulse=1;this.burstTime=1;const origin=this.planets?.[index]?.getWorldPosition(new T.Vector3())||new T.Vector3(5,4,0);this.sparkOrigin=origin;this.sparkVel=Array.from({length:180},()=>new T.Vector3((Math.random()-.5)*7,(Math.random()-.5)*7,(Math.random()-.5)*5));}
 transition(){if(!this.settings.paused&&!this.reduced.matches)this.pulse=.6;}
 wind(){const c=this.ctx,w=this.width,h=this.height,t=this.time;c.clearRect(0,0,w,h);if(!this.quotes.length)return;for(let row=0;row<6;row++){const cycle=t/15+row*.15,p=cycle%1,text=this.quotes[(Math.floor(cycle)+row)%this.quotes.length],words=text.split(/\s+/);c.font=`${w<650?17:24+row%3*4}px Georgia`;let x=w*.48+(row%2)*100-(p-.4)*w*.55;const y=h*(.2+row*.11);for(let j=0;j<words.length;j++){const phase=p-j*.008;c.globalAlpha=Math.max(0,Math.min(phase*7,(1-phase)*6,1))*.4;c.fillStyle=row%2?'#d9f1e5':'#efc996';c.fillText(words[j],x,y+Math.sin(t*.35+j*.35+row)*12+Math.pow(Math.max(0,p-.7),2)*120*Math.sin(j));x+=c.measureText(words[j]+' ').width;}}c.globalAlpha=1;}
 animate(ms){this.frame=requestAnimationFrame(this.animate);if(ms-this.last<1000/30)return;const dt=Math.min((ms-this.last)/1000||.03,.08);this.last=ms;if(document.hidden)return;const cfg=this.settings;if(!cfg.paused&&!this.reduced.matches)this.time+=dt*cfg.speed*(cfg.reading?.55:1);const e=cfg.paused||this.reduced.matches?0:this.energy.level;this.pulse=Math.max(0,this.pulse-dt*1.8);const t=this.time;
  if(cfg.scene==='wind')this.wind();
  if(!this.renderer)return;
  const px=cfg.paused||this.reduced.matches?0:this.pointer.x,py=cfg.paused||this.reduced.matches?0:this.pointer.y;
  if(cfg.scene==='ocean'){this.camera.position.set(px*.65,2.4+py*.15,12);this.camera.lookAt(0,1.2,-70);this.water.material.uniforms.time.value=t;this.water.material.uniforms.energy.value=(e?this.energy.bass:0)*cfg.soundStrength+this.pulse;}
  if(cfg.scene==='train'){this.camera.position.set(px*.5,4+py*.15,13);this.camera.lookAt(0,4,-65);for(const g of this.land.children){if(!g.isGroup)continue;if(g===this.scenery||g===this.village||g===this.fences){const span=g===this.fences?280:g===this.village?432:506;g.children.forEach(obj=>obj.position.x=((obj.userData.baseX+span/2-t*g.userData.speed)%span+span)%span-span/2);}else g.position.x=-(t*g.userData.speed%240);}}
  if(cfg.scene==='orbit'){this.camera.position.set(0,4,16);this.camera.lookAt(0,4,0);this.orbit.position.set(this.width<700?1:6,4,0);this.orbit.scale.setScalar(this.width<700?.42:1);this.core.rotation.y=t*.2;this.core.scale.setScalar(1+e*.22+this.pulse*.15);this.labels.forEach((l,i)=>{const a=t*.08+i*Math.PI*2/Math.max(1,this.words.length),r=this.lit.has(i)?2.1:3.4;l.position.set(Math.cos(a)*r,Math.sin(a*.6+i)*2,Math.sin(a)*r*.35);this.planets[i].position.copy(l.position).add(new T.Vector3(0,-.35,0));});}
  this.audioRing.visible=e>.002&&cfg.scene!=='wind';this.audioRing.position.set(cfg.scene==='orbit'?6:7,4,-4);this.audioRing.children.forEach((b,i)=>{const band=i%3===0?this.energy.bass:i%3===1?this.energy.mid:this.energy.high;b.scale.y=.4+band*cfg.soundStrength*14;});
  if(this.burstTime>0){this.burstTime=Math.max(0,this.burstTime-dt);const age=1-this.burstTime;for(let i=0;i<180;i++){const p=this.sparkOrigin.clone().addScaledVector(this.sparkVel[i],age);this.sparks.set([p.x,p.y,p.z],i*3);}this.sparkMesh.geometry.attributes.position.needsUpdate=true;this.sparkMesh.material.opacity=this.burstTime;}
  if(cfg.scene!=='wind')this.renderer.render(this.scene,this.camera);
 }
 snapshot(){return{triangles:this.renderer?.info.render.triangles||0,time:this.time,energy:this.energy.level,targets:(this.labels||[]).map(l=>{const p=l.getWorldPosition(new T.Vector3()).project(this.camera);return{index:l.userData.index,x:(p.x+1)*this.width/2,y:(1-p.y)*this.height/2};})};}
 dispose(){cancelAnimationFrame(this.frame);window.removeEventListener('pointermove',this.move);window.removeEventListener('pointerdown',this.pick);this.resizeObserver.disconnect();if(this.scene){const geos=new Set(),mats=new Set();this.scene.traverse(o=>{if(o.geometry)geos.add(o.geometry);if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>mats.add(m));});geos.forEach(g=>g.dispose());mats.forEach(m=>{m.map?.dispose();m.dispose();});}this.renderer?.dispose();this.host.replaceChildren();}
}
