import * as T from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import oceanURL from '../../../assets/yuejing/ocean.glb';
import islandURL from '../../../assets/yuejing/refined/book-island.glb';
import { scenePalette } from './palette';
import { atmosphereGLSL } from './sky-shader';
import { oceanVertex, oceanFragment } from './ocean-shader';
import { drawWind } from './wind-field';
import { buildBottles, animateBottles } from './sea-bottles';
function disposeObject(root){const g=new Set(),m=new Set(),textures=new Set();root?.traverse(o=>{if(o.geometry)g.add(o.geometry);for(const a of o.material?Array.isArray(o.material)?o.material:[o.material]:[]){m.add(a);for(const v of Object.values(a))if(v?.isTexture)textures.add(v);}});textures.forEach(t=>t.dispose());g.forEach(v=>v.dispose());m.forEach(v=>v.dispose());}
export class SceneEngine {
 constructor(host,onPick,onFailure){
  this.host=host;this.onPick=onPick;this.onFailure=onFailure;this.quotes=[];this.words=[];this.energy={bass:0,mid:0,high:0,level:0};this.time=0;this.last=0;this.pulse=0;this.gustPower=0;this.pointer=new T.Vector2();this.pointerTarget=new T.Vector2();this.scratch=new T.Vector3();this.windCache=new Map();this.pointerVelocity=new T.Vector2();this.lastPointerAt=-1000;this.seaResponse=0;this.dirty=true;this.settings={scene:'wind',mood:'dusk',speed:.7,intensity:.85,paused:false,soundStrength:1.8,theme:'paper',matchTheme:true};this.palette=scenePalette(this.settings);this.reduced=matchMedia('(prefers-reduced-motion: reduce)');this.models={ocean:'idle',island:'idle'};this.disposed=false;
  this.canvas=document.createElement('canvas');this.canvas.setAttribute('aria-label','随风生成的书中摘录');host.append(this.canvas);this.ctx=this.canvas.getContext('2d');
  this.move=e=>{const now=performance.now(),elapsed=Math.max(.016,(now-this.lastPointerAt)/1000),oldX=(this.pointerTarget.x+1)*this.width/2,oldY=(1-this.pointerTarget.y)*this.height/2;this.pointerVelocity.set((e.clientX-oldX)/elapsed,(e.clientY-oldY)/elapsed);this.pointerTarget.set(e.clientX/Math.max(1,this.width)*2-1,1-e.clientY/Math.max(1,this.height)*2);this.lastPointerAt=now;if(this.starPress&&Math.hypot(e.clientX-this.starPress.x,e.clientY-this.starPress.y)>12){clearTimeout(this.starTimer);this.starPress=null;}};
  this.pick=e=>{if(e.target.closest('button,input,select,textarea,a,[role=dialog],.reader-text,.yj-panel,.yj-overlay')&&!e.target.closest('.yj-orbit-window'))return;if(this.settings.scene==='wind'){this.gust();return;}if(!this.camera)return;const ray=new T.Raycaster();ray.setFromCamera(new T.Vector2(e.clientX/this.width*2-1,1-e.clientY/this.height*2),this.camera);
   if(this.settings.game&&this.labels){const hit=ray.intersectObjects(this.labels.filter(l=>l.visible))[0];if(hit)this.onPick?.(hit.object.userData.index);}
   else if(this.settings.scene==='orbit'&&!this.settings.reading&&ray.intersectObject(this.core)[0]){this.starPress={x:e.clientX,y:e.clientY,id:e.pointerId};this.starTimer=setTimeout(()=>{if(this.starPress){this.starPress=null;this.onStar?.();}},500);}
   else if(this.settings.scene==='ocean'&&this.bottles?.visible){const hit=ray.intersectObjects(this.bottles.children.filter(b=>b.visible),true)[0];if(hit){let b=hit.object;while(b.parent!==this.bottles)b=b.parent;this.selectedBottle=b.userData.index;this.onBottle?.();}else this.transition();}
  };
  this.release=e=>{clearTimeout(this.starTimer);if(this.starPress?.id===e.pointerId){this.starPress=null;if(e.type==='pointerup')this.onStar?.();}};
  this.scroll=()=>{this.dirty=true;};window.addEventListener('scroll',this.scroll,{capture:true,passive:true});window.addEventListener('pointermove',this.move);window.addEventListener('pointerdown',this.pick);window.addEventListener('pointerup',this.release);window.addEventListener('pointercancel',this.release);this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.resize();this.animate=this.animate.bind(this);this.frame=requestAnimationFrame(this.animate);
 }
 initialize3D(){if(this.renderer||this.renderError)return;try{
  this.renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;this.renderer.setClearColor(0,0);this.renderer.domElement.setAttribute('aria-label','Blender 海洋、云上书岛与词语星轨');this.host.append(this.renderer.domElement);this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(54,1,.1,1800);this.hemi=new T.HemisphereLight(0xc5e0e8,0x273f48,2);this.scene.add(this.hemi);this.light=new T.DirectionalLight(0xffdfb3,2.6);this.light.position.set(-18,28,12);this.scene.add(this.light);this.light.shadow.mapSize.set(1024,1024);Object.assign(this.light.shadow.camera,{left:-16,right:16,top:16,bottom:-16,near:.5,far:100});this.light.shadow.bias=-.0005;this.light.shadow.normalBias=.02;
  this.sunDir=new T.Vector3(-.38,.16,-1).normalize();this.sky=new T.Mesh(new T.SphereGeometry(1500,32,16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{time:{value:0},top:{value:new T.Color()},horizon:{value:new T.Color()},glow:{value:new T.Color()},sun:{value:this.sunDir}},vertexShader:'varying vec3 d;void main(){d=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec3 d;uniform float time;uniform vec3 top,horizon,glow,sun;${atmosphereGLSL}void main(){gl_FragColor=vec4(atmosphere(normalize(d),top,horizon,glow,sun,time),1.);\n#include <colorspace_fragment>\n}`}));this.scene.add(this.sky);
  this.oceanGroup=new T.Group();this.island=new T.Group();this.orbit=new T.Group();this.scene.add(this.oceanGroup,this.island,this.orbit);this.buildOcean();this.buildOrbit();this.buildClouds();this.resize();
 }catch(e){this.renderError=true;this.onFailure?.();}}
 buildOcean(){
  this.seaMaterial=new T.ShaderMaterial({uniforms:{time:{value:0},energy:{value:0},top:{value:new T.Color()},horizon:{value:new T.Color()},glow:{value:new T.Color()},sun:{value:this.sunDir},deep:{value:new T.Color()}},vertexShader:oceanVertex,fragmentShader:oceanFragment});
  const fallback=new T.PlaneGeometry(480,480,144,144);fallback.rotateX(-Math.PI/2);this.water=new T.Mesh(fallback,this.seaMaterial);this.oceanGroup.add(this.water);this.bottles=buildBottles();this.oceanGroup.add(this.bottles);
 }
 loadModel(name){if(this.models[name]!=='idle')return;this.models[name]='loading';new GLTFLoader().load(new URL(name==='ocean'?oceanURL:islandURL,import.meta.url).href,gltf=>{if(this.disposed){disposeObject(gltf.scene);return;}this.dirty=true;gltf.scene.updateMatrixWorld(true);
  if(name==='ocean'){let source;gltf.scene.traverse(o=>{if(o.isMesh&&!source)source=o;});if(!source){this.models.ocean='failed';return;}this.oceanGroup.remove(this.water);this.water.geometry.dispose();source.material.dispose();source.removeFromParent();this.water=source;this.water.material=this.seaMaterial;this.water.scale.set(4,1,4);this.oceanGroup.add(source);this.models.ocean='ready';}
  else{this.island.add(gltf.scene);this.pages=[];gltf.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}if(o.name.startsWith('FloatingPage')){o.userData.baseY=o.position.y;this.pages.push(o);}});this.models.island='ready';gltf.scene.traverse(o=>{if(o.material?.color)o.userData.baseColor=o.material.color.clone();});this.colourIsland();}
 },undefined,()=>{if(!this.disposed){this.models[name]='failed';this.onFailure?.();}});}
 buildClouds(){
  const c=document.createElement('canvas');c.width=256;c.height=128;const ctx=c.getContext('2d');
  for(let i=0;i<15;i++){const x=40+i*13,y=64+Math.sin(i*2.1)*13,r=18+(i%4)*7,g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,'rgba(255,255,255,.5)');g.addColorStop(.5,'rgba(235,241,242,.24)');g.addColorStop(1,'rgba(235,241,242,0)');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);}
  const texture=new T.CanvasTexture(c);this.clouds=new T.Group();for(let i=0;i<20;i++){const o=new T.Sprite(new T.SpriteMaterial({map:texture,transparent:true,opacity:.62,depthWrite:false}));o.position.set(Math.sin(i*2.4)*25,-2.9+(i%4)*.5,-7-(i%6)*7);o.scale.set(17+(i%3)*3,6+(i%2)*2,1);this.clouds.add(o);}this.scene.add(this.clouds);
 }
 buildOrbit(){
  this.core=new T.Mesh(new T.IcosahedronGeometry(2.05,2),new T.MeshBasicMaterial({color:0xd7bd97,wireframe:true,transparent:true,opacity:.58}));this.orbit.add(this.core);this.rings=[];
  for(let i=0;i<4;i++){const ring=new T.Mesh(new T.TorusGeometry(3.55+i*.62,.023,6,120),new T.MeshBasicMaterial({color:0xadc6cd,transparent:true,opacity:.46}));ring.rotation.set(.7+i*.8,.3+i*.6,i*.3);this.orbit.add(ring);this.rings.push(ring);}this.labels=[];this.planets=[];
  const points=[];let seed=1234;const rnd=()=>{seed=seed*16807%2147483647;return(seed-1)/2147483646;};for(let i=0;i<850;i++)points.push((rnd()-.5)*180,rnd()*85-30,-rnd()*140-20);const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(points,3));this.stars=new T.Points(geo,new T.PointsMaterial({color:0xeadcc1,size:.14,transparent:true,opacity:.7,depthWrite:false}));this.scene.add(this.stars);
  this.audioRing=new T.Group();for(let i=0;i<64;i++){const b=new T.Mesh(new T.BoxGeometry(.045,.1,.03),new T.MeshBasicMaterial({color:0xb7d4d5,transparent:true,opacity:.35}));const a=i/64*Math.PI*2;b.position.set(Math.cos(a)*3.2,Math.sin(a)*3.2,0);b.rotation.z=a-Math.PI/2;this.audioRing.add(b);}this.orbit.add(this.audioRing);
  this.sparks=new Float32Array(180*3);const sg=new T.BufferGeometry();sg.setAttribute('position',new T.BufferAttribute(this.sparks,3));this.sparkMesh=new T.Points(sg,new T.PointsMaterial({color:0xf6dab0,size:.075,transparent:true,opacity:0,depthTest:false}));this.scene.add(this.sparkMesh);
 }
 paintLabel(l,word,index){
  const colour=this.lit?.has(index)?this.palette.accent:this.palette.ink,key=word+'|'+colour;if(l.userData.paint===key)return;
  const c=document.createElement('canvas'),ctx=c.getContext('2d');ctx.font='500 40px Georgia,Microsoft YaHei';c.width=Math.ceil(ctx.measureText(word.slice(0,28)).width)+28;c.height=64;
  ctx.font='500 40px Georgia,Microsoft YaHei';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=colour;ctx.fillText(word.slice(0,28),c.width/2,32);
  l.material.map?.dispose();l.material.map=new T.CanvasTexture(c);l.material.map.colorSpace=T.SRGBColorSpace;l.material.needsUpdate=true;l.userData.aspect=c.width/64;l.userData.paint=key;
 }
 setWords(words,lit=new Set()){
  this.dirty=true;this.words=words.slice(0,48);this.lit=lit;if(!this.orbit)return;
  while(this.labels.length>this.words.length){const l=this.labels.pop(),p=this.planets.pop();this.orbit.remove(l,p);disposeObject(l);disposeObject(p);}
  this.words.forEach((word,i)=>{let l=this.labels[i];if(!l){l=new T.Sprite(new T.SpriteMaterial({transparent:true,depthTest:false}));l.userData.index=i;this.orbit.add(l);this.labels.push(l);const p=new T.Mesh(new T.SphereGeometry(.11+(i%3)*.025,12,8),new T.MeshBasicMaterial({transparent:true,opacity:.86}));this.orbit.add(p);this.planets.push(p);}this.paintLabel(l,word,i);this.planets[i].material.color.set(lit.has(i)?this.palette.accent:this.palette.ink);});
 }
 colourIsland(){const tint=new T.Color(this.palette.ground);this.island?.traverse(o=>{if(o.material?.color&&o.userData.baseColor)o.material.color.copy(o.userData.baseColor).lerp(tint,.10);});}
 configure(settings){
  this.dirty=true;const changed=this.settings.scene!==settings.scene,oldPalette=this.palette;this.settings=settings;this.orbitWindow=settings.game?document.querySelector('.yj-orbit-window'):null;this.palette=scenePalette(settings);
  if(changed||settings.reading||settings.game){clearTimeout(this.starTimer);this.starPress=null;}
  if(settings.scene!=='wind')this.initialize3D();this.canvas.hidden=settings.scene!=='wind';if(!this.renderer)return;
  this.renderer.domElement.hidden=settings.scene==='wind';this.oceanGroup.visible=settings.scene==='ocean';this.island.visible=settings.scene==='island';this.orbit.visible=settings.scene==='orbit';this.sky.visible=settings.scene!=='orbit';this.clouds.visible=settings.scene==='island';this.stars.visible=settings.scene==='orbit';this.scene.background=settings.scene==='orbit'?new T.Color(this.palette.space):null;this.audioRing.visible=false;this.sparkMesh.visible=settings.scene==='orbit';
  if(changed){this.pulse=0;this.burstTime=0;this.sparkMesh.material.opacity=0;this.renderer.clear();}
  const p=this.palette;for(const material of [this.sky.material,this.seaMaterial]){for(const k of ['top','horizon'])material.uniforms[k].value.set(p[k]);material.uniforms.glow.value.set(p.sun);}this.seaMaterial.uniforms.deep.value.set(p.water);
  this.sunDir.set(-.38,settings.mood==='night'?.31:settings.mood==='dawn'?.07:settings.mood==='dusk'?.10:.16,-1).normalize();this.hemi.color.set(p.horizon);this.hemi.groundColor.set(p.ground);this.light.castShadow=settings.scene==='island';this.light.color.set(p.sun);this.light.intensity=settings.theme==='night'&&settings.matchTheme!==false?1.8:2.5;
  this.core.material.color.set(p.accent);this.rings.forEach(r=>r.material.color.set(p.ink));this.stars.material.color.set(p.ink);this.sparkMesh.material.color.set(p.accent);this.audioRing.children.forEach(b=>b.material.color.set(p.accent));this.clouds.children.forEach(o=>o.material.color.set(p.horizon));
  if(settings.scene==='ocean'||settings.scene==='island')this.loadModel(settings.scene);if(this.labels.length!==this.words.length||oldPalette.ink!==p.ink||oldPalette.accent!==p.accent)this.setWords(this.words,this.lit);this.colourIsland();
 }
 resize(){this.dirty=true;const r=this.host.getBoundingClientRect();this.width=r.width||innerWidth;this.height=r.height||innerHeight;const d=Math.min(devicePixelRatio,1.5);this.canvas.width=this.width*d;this.canvas.height=this.height*d;this.ctx.setTransform(d,0,0,d,0,0);if(this.renderer){this.renderer.setSize(this.width,this.height);this.camera.aspect=this.width/this.height;this.camera.updateProjectionMatrix();}}
 gust(quote){this.dirty=true;if(quote){this.quotes=[quote,...this.quotes.filter(q=>q!==quote)].slice(0,24);this.time=7;}if(!this.settings.paused&&!this.reduced.matches)this.gustPower=1;this.wind();}
 transition(){if(!this.settings.paused&&!this.reduced.matches){this.pulse=.5;if(this.settings.scene==='wind')this.gustPower=.55;}}
 burst(index=0){if(this.settings.paused||this.reduced.matches)return;this.pulse=1;this.burstTime=1;this.sparkOrigin=this.planets?.[index]?.getWorldPosition(new T.Vector3())||new T.Vector3(5,4,0);this.sparkVel=Array.from({length:180},()=>new T.Vector3((Math.random()-.5)*7,(Math.random()-.5)*7,(Math.random()-.5)*5));}
 wind(dt){drawWind(this,dt);}
 castBottle(style='slender'){if(!this.bottles)return;const b=this.bottles.children.find(b=>b.userData.style===style)||this.bottles.children[0];b.userData.castAt=this.time;this.dirty=true;}
 collectBottle(){const b=this.bottles?.children[this.selectedBottle??0];if(b)b.userData.castAt=this.time;this.selectedBottle=undefined;this.dirty=true;}
 animateOrbit(t,e){
  this.camera.position.set(0,5,20);this.camera.lookAt(0,5,0);const mobile=this.width<760,game=this.settings.game,worldHeight=2*20*Math.tan(54*Math.PI/360),unit=worldHeight/this.height;
  const windowBox=mobile&&game?this.orbitWindow?.getBoundingClientRect():null;this.orbit.visible=!windowBox||(windowBox.bottom>0&&windowBox.top<this.height);
  const centerX=windowBox?windowBox.x+windowBox.width/2:mobile?this.width*.5:game?this.width*.755:this.width*.70,centerY=windowBox?windowBox.y+windowBox.height/2:this.height*.48;
  this.orbit.position.set((centerX-this.width/2)*unit,5+(this.height/2-centerY)*unit,0);const diameter=windowBox?Math.min(windowBox.width-22,windowBox.height*.9):mobile?Math.min(this.width-60,260):game?Math.min(this.width*.42,this.height*.78):Math.min(this.width*.65,this.height*.90);
  this.orbit.scale.setScalar(diameter*unit/12);this.core.rotation.set(t*.07,t*.15,t*.04);this.core.scale.setScalar(1+e*.14+this.pulse*.06);
  this.rings.forEach((r,i)=>r.rotation.set(.65+i*.71+Math.sin(t*.11+i)*.13,.28+i*.5+t*(i%2?-.035:.045),i*.31+t*.055));
  this.orbit.updateMatrixWorld(true);const scale=this.orbit.scale.x;this.starTarget={x:centerX,y:centerY,r:2.05*scale/unit};if(!game&&!this.settings.reading)this.onStarLayout?.(centerX,centerY,this.starTarget.r);
  this.labels.forEach((l,i)=>{const ring=Math.floor(i/12),a=this.settings.game&&i<3?t*.07+i*Math.PI*2/3:t*(.07+ring*.009)+i*Math.PI*2/Math.min(12,this.words.length)+ring*.54,r=4.25+ring*.48;
   l.position.set(Math.cos(a)*r,Math.sin(a)*r*.67+Math.sin(a*2+ring)*.22,Math.sin(a+.5)*r*.28);this.planets[i].position.copy(l.position);this.planets[i].position.y-=.28;
   const distance=20-l.position.z*scale,worldPixel=2*distance*Math.tan(54*Math.PI/360)/this.height,pixelHeight=mobile?25.6:32;
   l.scale.set(l.userData.aspect*pixelHeight*worldPixel/scale,pixelHeight*worldPixel/scale,1);l.userData.fontPixels=pixelHeight*40/64;l.visible=true;
  });
  this.orbit.updateMatrixWorld(true);const occupied=[];
  this.labels.forEach(l=>{this.scratch.copy(l.position).applyMatrix4(this.orbit.matrixWorld).project(this.camera);const x=(this.scratch.x+1)*this.width/2,y=(1-this.scratch.y)*this.height/2,h=l.userData.fontPixels+8,w=l.userData.aspect*h,rect={x:x-w/2,y:y-h/2,w,h};
   l.visible=!occupied.some(o=>rect.x<o.x+o.w+5&&rect.x+rect.w+5>o.x&&rect.y<o.y+o.h+4&&rect.y+rect.h+4>o.y);if(l.visible)occupied.push(rect);
  });
  this.audioRing.visible=e>.002;this.audioRing.children.forEach((b,i)=>{const band=i%3===0?this.energy.bass:i%3===1?this.energy.mid:this.energy.high;b.scale.y=.3+band*this.settings.soundStrength*8;});
 }
 animate(ms){
  this.frame=requestAnimationFrame(this.animate);if(ms-this.last<1000/30)return;const dt=Math.min((ms-this.last)/1000||.03,.08);this.last=ms;if(this.disposed||document.hidden)return;
  const cfg=this.settings,moving=!cfg.paused&&!this.reduced.matches;if(this.wasMoving!==moving){this.wasMoving=moving;this.dirty=true;}if(!moving&&!this.dirty)return;this.dirty=false;if(moving){this.time+=dt*cfg.speed;this.pointer.lerp(this.pointerTarget,1-Math.exp(-dt*8));this.pulse=Math.max(0,this.pulse-dt*.8);this.gustPower=Math.max(0,this.gustPower-dt*.32);}const e=moving?this.energy.level:0,t=this.time;
  if(cfg.scene==='wind'){this.wind(dt);return;}if(!this.renderer||this.renderError)return;const px=moving?this.pointer.x:0,py=moving?this.pointer.y:0;this.sky.material.uniforms.time.value=t;
  if(cfg.scene==='ocean'){this.camera.position.set(px*.35,3.6+py*.12,14);this.camera.lookAt(0,1.55,-120);this.seaMaterial.uniforms.time.value=t;const raw=moving?Math.min(1.6,Math.pow(Math.max(0,this.energy.bass*.75+this.energy.level*.25-.018),.68)*cfg.soundStrength*1.35):0;this.seaResponse+=(raw-this.seaResponse)*(1-Math.exp(-dt*(raw>this.seaResponse?12:4)));if(!moving)this.seaResponse=0;this.seaMaterial.uniforms.energy.value=this.seaResponse;animateBottles(this,t);const weights=this.water.morphTargetInfluences;if(weights){weights.fill(0);const phase=t*.5,a=Math.floor(phase)%4,b=(a+1)%4,f=phase%1;if(a>0)weights[a-1]=1-f;if(b>0)weights[b-1]=f;}}
  if(cfg.scene==='island'){this.camera.position.set(9+px*.5,8.8+py*.25,19);this.camera.lookAt(1.4,.7,0);this.island.position.set(this.width<760?1.1:4.5,Math.sin(t*.25)*.13,0);this.island.rotation.y=-.14+Math.sin(t*.09)*.09+px*.04;this.island.scale.setScalar(this.width<760?.72:1.1);this.pages?.forEach((p,i)=>p.position.y=p.userData.baseY+Math.sin(t*.35+i)*.17);this.clouds.position.x=Math.sin(t*.03)*4;}
  if(cfg.scene==='orbit')this.animateOrbit(t,e);
  if(this.burstTime>0&&moving){this.burstTime=Math.max(0,this.burstTime-dt);const age=1-this.burstTime;for(let i=0;i<180;i++){this.scratch.copy(this.sparkOrigin).addScaledVector(this.sparkVel[i],age);this.sparks[i*3]=this.scratch.x;this.sparks[i*3+1]=this.scratch.y;this.sparks[i*3+2]=this.scratch.z;}this.sparkMesh.geometry.attributes.position.needsUpdate=true;this.sparkMesh.material.opacity=this.burstTime;}
  this.renderer.render(this.scene,this.camera);
 }
 snapshot(){return{starTarget:this.starTarget,seaResponse:this.seaResponse,windTargets:this.windTargets||[],maxPluck:this.maxPluck||0,bottles:(this.bottles?.visible?this.bottles.children.filter(b=>b.visible):[]).map(b=>{const p=b.localToWorld(new T.Vector3(0,.6,0)).project(this.camera);return{style:b.userData.style,x:(p.x+1)*this.width/2,y:(1-p.y)*this.height/2,world:b.position.toArray()};}),triangles:this.renderer?.info.render.triangles||0,renderFrames:this.renderer?.info.render.frame||0,time:this.time,energy:this.energy.level,activeScene:this.settings.scene,theme:this.settings.theme,palette:{...this.palette},rings:this.rings?.map(r=>r.rotation.toArray().slice(0,3))||[],visibleLayers:[this.canvas.hidden?null:'wind',this.oceanGroup?.visible?'ocean':null,this.island?.visible?'island':null,this.stars?.visible?'orbit':null].filter(Boolean),models:{...this.models},stars:this.stars?.geometry.attributes.position.count||0,planetCount:this.words.length,gust:this.gustPower,pointer:[this.pointerTarget.x,this.pointerTarget.y],smoothPointer:[this.pointer.x,this.pointer.y],geometries:this.renderer?.info.memory.geometries||0,targets:(this.labels||[]).filter(l=>l.visible).map(l=>{const p=l.getWorldPosition(new T.Vector3()).project(this.camera);return{index:l.userData.index,x:(p.x+1)*this.width/2,y:(1-p.y)*this.height/2,fontPixels:l.userData.fontPixels};})};}
 dispose(){this.disposed=true;cancelAnimationFrame(this.frame);window.removeEventListener('scroll',this.scroll,true);window.removeEventListener('pointermove',this.move);window.removeEventListener('pointerdown',this.pick);window.removeEventListener('pointerup',this.release);window.removeEventListener('pointercancel',this.release);clearTimeout(this.starTimer);this.resizeObserver.disconnect();disposeObject(this.scene);this.renderer?.dispose();this.renderer?.forceContextLoss();this.host.replaceChildren();}
}
