import React, { useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import type { Book, Notebook, ReaderNote, VocabItem, YujingSettings, ThemeName } from "../../shared/types";
import { DEFAULT_YUJING } from "../../shared/defaults";
import type { SceneEngine } from "./scene-engine";
import { AtmosphereAudio, type AudioEnergy } from "./audio";
import { gamePalette } from "./palette";
import "./yujing.css";
type Props = { settings?: YujingSettings; theme?:ThemeName; save: (settings:YujingSettings)=>void; view:"library"|"reader"; book:Book|null; chapterText:string; chapterTitle?:string; notes:ReaderNote[]; vocab:VocabItem[]; notebooks:Notebook[]; selectedText:string; capture:()=>Promise<unknown>; home:()=>void; pageKey:string; lab?:boolean };
type Word={word:string;meaning:string;example:string;item:VocabItem};
const scenes=[['wind','风中的句子'],['ocean','海的慢呼吸'],['island','云上书岛'],['orbit','词语星轨']] as const;
export function YuejingEntry({enabled,nav=false}:{enabled:boolean;nav?:boolean}) {
 return <button className={`yj-toggle yj-entry ${nav?'yj-entry-nav':''}`} aria-label="跃境" title="跃境 · 背景与刷词" data-enabled={enabled} onClick={()=>window.dispatchEvent(new Event('skipreader:atmosphere-open'))}><svg aria-hidden="true" width="19" height="19" viewBox="0 0 24 24" fill="none"><path d="M12 3l2.6 6.4L21 12l-6.4 2.6L12 21l-2.6-6.4L3 12l6.4-2.6L12 3z" stroke="currentColor" strokeWidth="1.4"/><circle cx="19" cy="4" r="1.5" fill="currentColor"/></svg><b>跃境</b>{nav&&<small>{enabled?'已开启':'背景与刷词'}</small>}{enabled&&<i aria-label="已开启"/>}</button>;
}
function maskWord(example:string,word:string) {
 const escaped=word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
 const pattern=/[\p{Script=Han}]/u.test(word)?escaped:`(?<![\\p{Script=Latin}\\p{N}_])${escaped}(?![\\p{Script=Latin}\\p{N}_])`;
 return example.replace(new RegExp(pattern,'giu'),'______');
}
export function Yujing(props:Props){
 const cfg=props.settings||DEFAULT_YUJING,host=useRef<HTMLDivElement>(null),engine=useRef<SceneEngine>(),audio=useRef<AtmosphereAudio>();
 const [ready,setReady]=useState(0),[panel,setPanel]=useState(false),[gameOpen,setGameOpen]=useState(false),[failed,setFailed]=useState(false),[sound,setSound]=useState('声音未连接'),[message,setMessage]=useState(''),[manual,setManual]=useState(cfg.manualQuotes.join('\n'));
 const [scope,setScope]=useState(props.book?'book':'all'),[round,setRound]=useState(0),[queue,setQueue]=useState<number[]>([]),[score,setScore]=useState(0),[combo,setCombo]=useState(0),[lit,setLit]=useState<Set<number>>(new Set()),[answered,setAnswered]=useState(false),[wrong,setWrong]=useState<Set<number>>(new Set()),[feedback,setFeedback]=useState(''),[autoNext,setAutoNext]=useState(true),[mode,setMode]=useState<'quiz'|'recall'>('quiz'),[revealed,setRevealed]=useState(false);
 const answerRef=useRef<(index:number)=>void>(()=>{}),advanceTimer=useRef<number>(),gameCard=useRef<HTMLDivElement>(null),openButton=useRef<HTMLButtonElement>(null);
 const pickMap=useRef<number[]>([]),energyBar=useRef<HTMLDivElement>(null),audioLabel=useRef('声音未连接'),audioEnergy=useRef<AudioEnergy>({bass:0,mid:0,high:0,level:0});
 const update=(patch:Partial<YujingSettings>)=>props.save({...cfg,...patch});
 useEffect(()=>{const open=()=>setPanel(p=>!p);window.addEventListener('skipreader:atmosphere-open',open);return()=>window.removeEventListener('skipreader:atmosphere-open',open);},[]);
 useEffect(()=>{const captured=(event:Event)=>{engine.current?.gust((event as CustomEvent<string>).detail);};window.addEventListener('skipreader:wind-captured',captured);return()=>window.removeEventListener('skipreader:wind-captured',captured);},[]);
 const words=useMemo(()=>{const seen=new Set<string>();const filtered=props.vocab.filter(v=>scope==='book'?v.bookId===props.book?.id:scope==='all'||v.notebookId===scope);return filtered.flatMap(item=>{const key=item.word.trim().toLowerCase(),meaning=(item.chineseDef||item.englishDef||'').trim();if(!key||!meaning||seen.has(key))return[];seen.add(key);return[{word:item.word,meaning:meaning.slice(0,200),example:(item.sourceSentence||item.example||'').slice(0,300),item}];}).slice(0,48);},[props.vocab,scope,props.book?.id]);
 const quotes=useMemo(()=>{if(cfg.source==='manual')return cfg.manualQuotes;const notes=props.notes.filter(n=>props.view!=='reader'||n.bookId===props.book?.id).map(n=>n.selectedText.trim()).filter(Boolean).slice(0,24);if(cfg.source==='highlights'&&notes.length)return notes;return props.chapterText.slice(0,60000).split(/(?<=[。！？])|(?<=[.!?])\s+|\n+/).map(s=>s.trim()).filter(s=>s.length>=2&&s.length<600).slice(0,24);},[cfg.source,cfg.manualQuotes,props.notes,props.chapterText,props.book?.id,props.view]);
 const shuffle=(a:number[])=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
 const choices=useMemo(()=>!words[queue[0]]?[]:shuffle([queue[0],...shuffle(words.map((_,i)=>i).filter(i=>i!==queue[0])).slice(0,2)]),[queue[0],round,words]);
 useEffect(()=>{if(!cfg.enabled||!host.current)return;setFailed(false);let disposed=false,instance:SceneEngine|undefined;void import('./scene-engine').then(module=>{if(disposed||!host.current)return;instance=new module.SceneEngine(host.current,index=>answerRef.current(pickMap.current[index]??index),()=>setFailed(true));engine.current=instance;setReady(v=>v+1);}).catch(()=>setFailed(true));return()=>{disposed=true;instance?.dispose();engine.current=undefined;};},[cfg.enabled]);
 useEffect(()=>{engine.current?.configure({...cfg,theme:props.theme||'paper',scene:gameOpen?'orbit':cfg.scene,reading:props.view==='reader',game:gameOpen});if(engine.current)engine.current.quotes=quotes;},[cfg,quotes,gameOpen,props.view,props.theme,ready]);
 useEffect(()=>{const all=words.map((_,i)=>i);const indices=[...(gameOpen&&mode==='quiz'?choices:[]),...all.filter(i=>!gameOpen||mode!=='quiz'||!choices.includes(i))].slice(0,cfg.planetCount);pickMap.current=indices;engine.current?.setWords(indices.map(i=>words[i]?.word||''),new Set(indices.flatMap((index,i)=>lit.has(index)?[i]:[])));},[words,lit,cfg.enabled,ready,choices,gameOpen,mode,cfg.planetCount]);
 useEffect(()=>{engine.current?.transition();},[props.pageKey,props.view]);
 useEffect(()=>{let lastMeter=0;const controller=new AtmosphereAudio((label,e)=>{if(audioLabel.current!==label){audioLabel.current=label;setSound(label);}audioEnergy.current=e;if(engine.current)engine.current.energy=e;const now=performance.now();if(now-lastMeter>100||e.level===0){lastMeter=now;if(energyBar.current)energyBar.current.style.width=`${e.level*100}%`;}});audio.current=controller;const cleanup=()=>void controller.stop(false);window.addEventListener('pagehide',cleanup);return()=>{window.removeEventListener('pagehide',cleanup);cleanup();};},[]);
 useEffect(()=>{if(!cfg.enabled){void audio.current?.stop();setGameOpen(false);}},[cfg.enabled]);
 useLayoutEffect(()=>{const root=host.current?.closest('.app-shell,.yj-lab');root?.classList.toggle('yj-playing',gameOpen);return()=>{root?.classList.remove('yj-playing');};},[gameOpen,ready,cfg.enabled,props.view]);
 useEffect(()=>()=>{delete(window as any).skipReaderYujingSnapshot;},[]);
 function reset(){clearTimeout(advanceTimer.current);setQueue(shuffle(words.map((_,i)=>i)));setScore(0);setCombo(0);setLit(new Set());setRound(v=>v+1);setFeedback('按 1、2、3 选词，也可以点击选项。');setAnswered(false);setWrong(new Set());setRevealed(false);}
 useLayoutEffect(()=>{reset();},[words,mode]);

 useEffect(()=>()=>clearTimeout(advanceTimer.current),[]);
 function advance(){clearTimeout(advanceTimer.current);setQueue(q=>q.slice(1));setAnswered(false);setWrong(new Set());setRevealed(false);setFeedback('下一颗星，继续。');}
 function answer(index:number){if(!gameOpen||!queue.length||answered||!words[index])return;const target=queue[0];if(index!==target){setWrong(s=>new Set(s).add(index));setCombo(0);setFeedback(`${words[index].word}：${words[index].meaning}。再试一次。`);return;}const gained=100+Math.min(combo,4)*25;setScore(s=>s+gained);setCombo(c=>c+1);setLit(s=>new Set(s).add(target));setAnswered(true);setFeedback(`+${gained} 星光${combo>0?` · ${combo+1} 连击`:''}　${words[target].word}`);engine.current?.burst(pickMap.current.indexOf(target));if(autoNext)advanceTimer.current=window.setTimeout(advance,950);}
 answerRef.current=answer;
 function openGame(){setScope(props.book&&props.view==='reader'?'book':'all');update({enabled:true});setPanel(false);setGameOpen(true);reset();window.setTimeout(()=>gameCard.current?.focus(),60);}
 function closeGame(){clearTimeout(advanceTimer.current);setGameOpen(false);window.setTimeout(()=>openButton.current?.focus(),0);}
 function remember(known:boolean){setRevealed(false);const target=queue[0];if(known){setLit(s=>new Set(s).add(target));engine.current?.burst(target);setQueue(q=>q.slice(1));}else setQueue(q=>q.slice(1).concat(target));setFeedback(known?'记住了，下一词。':'这个词会在下一圈回来。');}
 useLayoutEffect(()=>{if(!gameOpen&&!panel)return;const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(panel)setPanel(false);else closeGame();return;}if(!gameOpen||panel||!queue.length||((e.target as HTMLElement)?.closest('textarea,select,input:not([type=checkbox])')))return;if(e.key===' '&&!answered&&(e.target as HTMLElement)?.matches('input[type=checkbox]'))return;if(['1','2','3',' ','ArrowRight'].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();if(mode==='recall'){if(e.key===' '&&!revealed)setRevealed(true);else if(revealed&&e.key==='1')remember(true);else if(revealed&&e.key==='2')remember(false);}else if(e.key===' '||e.key==='ArrowRight'){if(answered)advance();}else{const i=choices[Number(e.key)-1];if(i!==undefined)answer(i);}}};window.addEventListener('keydown',handler,true);return()=>window.removeEventListener('keydown',handler,true);},[gameOpen,panel,choices,answered,autoNext,queue,combo,words,mode,revealed]);
 useEffect(()=>{if(!panel)return;const dismiss=(e:PointerEvent)=>{if(!(e.target as HTMLElement).closest('.yj-panel,.yj-toggle'))setPanel(false);};document.addEventListener('pointerdown',dismiss);return()=>document.removeEventListener('pointerdown',dismiss);},[panel]);
 function updateQuotes(){const next=manual.split(/\r?\n/).map(q=>q.trim().slice(0,500)).filter(Boolean).slice(0,24);update({manualQuotes:next});engine.current?.gust(next[0]);setMessage(`已更新 ${next.length} 条摘录。`);}
 const run=(task:Promise<unknown>)=>{setMessage('');void task.catch(e=>{setMessage(e.message);});};
 const target=words[queue[0]],playing=gameOpen&&queue.length>0&&!!target,done=gameOpen&&words.length>0&&!queue.length;
 useEffect(()=>{(window as any).skipReaderYujingSnapshot=()=>{const render=engine.current?.snapshot();return{enabled:cfg.enabled,scene:gameOpen?'orbit':cfg.scene,panel,gameOpen,score,combo,learned:lit.size,queue:[...queue],choices:[...choices],answered,revealed,mode,quotes,wordCount:words.length,audio:sound,energy:audioEnergy.current.level,...render,targets:render?.targets.map(t=>({...t,index:pickMap.current[t.index]}))};};},[cfg,panel,gameOpen,score,combo,lit,queue,choices,answered,revealed,mode,quotes,words,sound]);
 return <>
  {cfg.enabled&&<div className={`yj-backdrop ${props.view==='reader'?'yj-reading':''} ${gameOpen?'yj-orbit':''}`} style={{opacity:gameOpen?1:cfg.intensity}}><div ref={host} className="yj-scene"/><div className="yj-veil"/></div>}
  {props.lab&&<div className={`yj-launch ${gameOpen?'yj-launch-game':''}`}><button ref={openButton} className="yj-toggle" aria-expanded={panel} onClick={()=>setPanel(p=>!p)}>✦ 跃境</button></div>}
  {panel&&<aside className="yj-panel" aria-label="调节气候"><div className="yj-panel-title"><h2>调节气候</h2><button aria-label="关闭气候设置" onClick={()=>setPanel(false)}>×</button></div><label className="yj-check"><input type="checkbox" checked={cfg.enabled} onChange={e=>update({enabled:e.target.checked})}/>开启跃境背景</label><p className="yj-help">书页之外，给想象一个地方。</p>{cfg.enabled&&<button className="yj-off" onClick={()=>{update({enabled:false});setPanel(false);setGameOpen(false);}}>关闭跃境 · 恢复普通阅读</button>}
   <div className="yj-scene-picks">{scenes.map(([id,title])=><button key={id} aria-pressed={cfg.scene===id} onClick={()=>{update({enabled:true,scene:id});clearTimeout(advanceTimer.current);setGameOpen(false);}}>{title}</button>)}</div>
   <button className="yj-primary" onClick={openGame}>进入词语星轨 · 快速刷词</button>
   <label className="yj-check"><input type="checkbox" checked={cfg.matchTheme!==false} onChange={e=>update({matchTheme:e.target.checked})}/>背景跟随应用主题</label>
   <label>光的时刻<select value={cfg.mood} onChange={e=>update({mood:e.target.value as YujingSettings['mood']})}><option value="day">晴海 · 剔透青蓝</option><option value="dawn">日出 · 桃金</option><option value="dusk">黄昏 · 暖霞</option><option value="night">夜航 · 深蓝</option></select></label>
   <label>流动速度<input type="range" min="0" max="1.5" step=".1" value={cfg.speed} onChange={e=>update({speed:Number(e.target.value)})}/></label><label>背景强度<input type="range" min=".1" max="1" step=".05" value={cfg.intensity} onChange={e=>update({intensity:Number(e.target.value)})}/></label><button onClick={()=>update({paused:!cfg.paused})}>{cfg.paused?'继续流动':'暂停流动'}</button>
   <label>阅读底色不透明度 · {Math.round(cfg.readerOpacity*100)}%<input aria-label="阅读底色不透明度" type="range" min="0" max="1" step=".05" value={cfg.readerOpacity} onChange={e=>update({readerOpacity:Number(e.target.value)})}/></label><p className="yj-help">往左拖，背景更清楚；往右拖，文字底色更实。</p><label>轨道词语数<input aria-label="轨道词语数" type="range" min="8" max="48" step="1" value={cfg.planetCount} onChange={e=>update({planetCount:Number(e.target.value)})}/></label><label>与原有图片背景<select value={cfg.blend} onChange={e=>update({blend:e.target.value as 'art'|'mix'})}><option value="art">跃境暂时替换图片</option><option value="mix">跃境与图片叠加</option></select></label>
   {cfg.scene==='wind'&&<><label>吹来的文字<select value={cfg.source} onChange={e=>update({source:e.target.value as YujingSettings['source']})}><option value="highlights">我的划线{props.book?' · 当前书籍':''}</option><option value="chapter" disabled={!props.chapterText}>当前阅读章节</option><option value="manual">手动摘录</option></select></label><p className="yj-help">已取 {quotes.length} 条。没有划线时，可使用当前章节；不会联网发送书中文字。</p>{cfg.source==='manual'&&<><textarea aria-label="手动摘录" rows={4} value={manual} onChange={e=>setManual(e.target.value)} maxLength={6000}/><button onClick={updateQuotes}>更新摘录</button></>}{quotes[0]&&<blockquote className="yj-source-preview">{quotes[0]}</blockquote>}{!quotes.length&&<p className="yj-help">暂无摘录。可以打开一本书、选中句子，或切换到手动摘录。</p>}{props.view==='reader'&&<button className="yj-capture" disabled={!props.selectedText.trim()} onPointerDown={e=>e.preventDefault()} onClick={()=>run(props.capture().then(note=>{if(note===null){setMessage('先在正文中拖选一句话，再点选句入风。');return;}update({source:'highlights'});engine.current?.gust(props.selectedText);setMessage('这句话已保存为划线，并送入风中。');}))}>选句入风</button>}</>}
   <h3>让声音变成形状</h3><span className="yj-audio-state">{sound}</span><div className="yj-energy" aria-label="声音能量"><div ref={energyBar} style={{width:`${audioEnergy.current.level*100}%`}}/></div><p className="yj-help">低音推动波浪，中高音拉伸能量环。声音连上后，试着切到海面或星轨。</p><div className="yj-two"><button onClick={()=>{update({enabled:true});run(audio.current!.demo());}}>试听律动</button><button onClick={()=>run(audio.current!.stop())}>停止 / 断开</button></div><label className="yj-file">本地音乐<input type="file" accept="audio/*" onChange={e=>{const f=e.target.files?.[0];if(f){update({enabled:true});run(audio.current!.file(f));}}}/></label><button onClick={()=>{update({enabled:true});run(audio.current!.share(true));}}>连接电脑系统声音</button><button onClick={()=>{update({enabled:true});run(audio.current!.share(false));}}>连接标签页声音</button><p className="yj-help">电脑声音：在 Windows Edge / Chrome 选择「整个屏幕」，勾选系统音频。无需展开播放器。部分浏览器仅支持标签页音轨。只分析音频，不读取或保存画面。</p><label>试听 / 文件音量<input type="range" min="0" max=".5" step=".01" defaultValue=".12" onChange={e=>audio.current?.setVolume(Number(e.target.value))}/></label><label>律动幅度<input type="range" min=".5" max="3" step=".1" value={cfg.soundStrength} onChange={e=>update({soundStrength:Number(e.target.value)})}/></label>{failed&&<p role="alert">此浏览器未能启动 3D，可使用文字风景或关闭跃境。</p>}{message&&<p className="yj-message" role="status">{message}</p>}
  </aside>}
  {gameOpen&&<section className="yj-play" style={gamePalette(props.theme) as React.CSSProperties}><div className="yj-game-card" role="dialog" aria-modal="true" aria-label="词语星轨刷词" ref={gameCard} tabIndex={-1}><div className="yj-game-top"><button onClick={closeGame}>← 回到 SkipReader</button><button onClick={()=>setPanel(p=>!p)}>气候与声音</button></div><h1>词语星轨</h1><p className="yj-game-intro">从读过的句子里，把单词重新点亮。</p><div className="yj-orbit-window" aria-hidden="true"/><div className="yj-game-controls"><label>词语来源<select aria-label="词语来源" value={scope} onChange={e=>setScope(e.target.value)}><option value="all">全部生词</option>{props.book&&<option value="book">当前书籍</option>}{props.notebooks.map(n=><option value={n.id} key={n.id}>{n.name}</option>)}</select></label><label>练习方式<select aria-label="练习方式" value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="quiz">捕词挑战</option><option value="recall">主动回想</option></select></label></div>
   <div className="yj-score"><span>星光 <b>{score}</b></span><span>连击 <b>{combo}</b></span><span>{lit.size} / {words.length} 已点亮</span></div>
   {!words.length&&<div className="yj-empty"><h2>先收藏几个词，再来点亮星轨。</h2><p>自动读取你保存的中文／英文释义和原句。缺少释义的词暂不出题；不会用示例替代你的生词。</p><button onClick={closeGame}>返回阅读，收藏生词</button></div>}
   {playing&&<><div className="yj-question"><small>{mode==='quiz'?'寻找这个意思的英文词':'先回想词义，再揭晓'}</small><h2>{mode==='quiz'?target.meaning:target.word}</h2>{mode==='recall'&&revealed&&<p>{target.meaning}</p>}<div className="yj-example"><small>原文例句 · {target.item.bookTitle || (target.item.bookId===props.book?.id?props.book?.title:'收藏的句子') || '收藏的句子'}</small><p>{target.example?mode==='quiz'&&!answered?maskWord(target.example,target.word):target.example:'这个词还没有收藏例句。'}</p></div></div>{mode==='quiz'?<div className="yj-choices">{choices.filter(index=>!!words[index]).map((index,i)=><button key={`${round}-${queue[0]}-${index}`} disabled={answered||wrong.has(index)} className={answered&&index===queue[0]?'yj-correct':wrong.has(index)?'yj-wrong':''} onClick={()=>answer(index)}><kbd>{i+1}</kbd>{words[index].word}</button>)}</div>:<div className="yj-choices">{!revealed?<button onClick={()=>setRevealed(true)}>空格 · 揭晓</button>:<><button onClick={()=>remember(true)}>1 · 记住了</button><button onClick={()=>remember(false)}>2 · 再来一圈</button></>}</div>}<p className="yj-feedback" role="status" aria-live="polite">{feedback}</p>{mode==='quiz'&&<div className="yj-flow"><label><input type="checkbox" checked={autoNext} onChange={e=>{setAutoNext(e.target.checked);if(!e.target.checked)clearTimeout(advanceTimer.current);}}/>自动下一题</label>{answered&&<button onClick={advance}>下一题 · 空格 →</button>}</div>}</>}
   {done&&<div className="yj-complete"><span>✦</span><h2>这一圈，全部点亮。</h2><p>{score} 点星光 · {words.length} 个词</p><button className="yj-primary" onClick={reset}>再来一圈 ↗</button></div>}
   {words.length>0&&<div className="yj-progress" role="progressbar" aria-label="星轨进度" aria-valuenow={lit.size} aria-valuemin={0} aria-valuemax={words.length}><div style={{width:`${lit.size/words.length*100}%`}}/></div>}<p className="yj-help">本轮游戏进度不改写生词和笔记。关闭跃境即可恢复普通界面。</p>
  </div></section>}
 </>;
}
